dist/libblockdev.spec
Avoid claiming ownership of system directories, and split the devel
packages so that each includes only the headers relevant to the
particular package.
Also the .gir file is a devel file.
=> Make package file paths more specific

src/lib/plugin_apis/btrfs.api, src/plugins/btrfs.c, tests/btrfs_test.py
Resolves: rhbz#1201120
When processing subvolumes, it is often desirable to process the parent
(sub)volume first because child subvolumes often have references to their
parents. That's why we need to sort subvolumes that way when returning a list of
them.
=> Sort BTRFS subvolumes in a way that child never appears before parent

site_scons/boilerplate_generator.py, src/lib/blockdev.c, src/lib/blockdev.h, src/lib/plugin_apis/crypto.api, src/lib/plugin_apis/lvm.api, src/lib/plugin_apis/mdraid.api, src/lib/test_blockdev.c, src/plugins/crypto.c, src/plugins/crypto.h, src/plugins/lvm.c, src/plugins/lvm.h, src/plugins/mdraid.c, src/plugins/mdraid.h, src/plugins/test_lvm.c, tests/library_test.py
As the commit message of the first commit explains:
> Printing out some message to stderr is not "loud enough" even if it is CRITICAL
and can be silently ignored (especially if the stderr is redirected somewhere).
We need to report error/raise exception if an unimplemented function is called.
Such error/exception can be handled by the caller just fine or they can
propagate it if they want to.
I know there could be improvements making the code a bit nicer (using pointers to load/unload functions and for-cycles instead of calling each of them separately) and further improvements (like adding the ``bd_unload()`` function to unload the library), but I'm leaving that for future development.
=> Make unimplemented libblockdev methods raise an exception (#1201475)

src/python/gi/overrides/BlockDev.py
pylint is not clever enough to figure this out.
=> Disable pylint checking on the new exception proxy.

Sconscript, src/lib/plugin_apis/mpath.api, src/plugins/mpath.c, src/plugins/mpath.h
This way we don't have to call the 'multipath' binary which is suboptimal.
=> Reimplement the is_mpath_member() function using device mapper

Makefile, Sconscript, dist/libblockdev.spec, docs/libblockdev-docs.xml, docs/libblockdev-sections.txt, features.rst, site_scons/boilerplate_generator.py, src/lib/blockdev.c, src/lib/plugin_apis/btrfs.api, src/lib/plugin_apis/kbd.api, src/lib/plugin_apis/lvm.api, src/lib/plugin_apis/mdraid.api, src/lib/plugins.c, src/lib/plugins.h, src/plugins/btrfs.c, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/kbd.c, src/plugins/kbd.h, src/plugins/lvm.c, src/plugins/mdraid.c, src/python/gi/overrides/BlockDev.py, tests/kbd_test.py, tests/utils.py
These commits implement the KernelBlockDevices plugin as it was planned before.
I'm sorry for the commit 09a61a2, but when I got to ``time.sleep(10)`` basically between every two lines of the ``bcache`` tests, I have up and just excluded the tests from normal runs. I run the myself as I know how to get the system back to the original state if some *bcache magic* happens.
=> The KBD plugin

src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h
By default GIOChannel expects data to be UTF-8, and this data definitely
isn't.
=> Set encoding to NULL before writing the escrow packet.

src/lib/blockdev.c, src/lib/blockdev.h, src/python/gi/overrides/BlockDev.py, tests/library_test.py
This tries to address the issue #15 by renaming the ``try_init()`` function to ``ensure_init()`` which is a better name for what it does and by adding new ``try_init()`` and ``try_reinit()`` functions that do "best-effort" plugin loading and report back the list of loaded plugins.
=> Make the init functions better usable

docs/libblockdev-sections.txt
This was the easy gtkdoc warning to fix.
=> Remove private macros from the gtkdoc sections file.

src/python/gi/overrides/BlockDev.py
Its 'discard' parameter should default to 'False' as that covers majority of use
cases.
This is an alternative solution for an issue targetted by (blivet's PR 121) [https://github.com/rhinstaller/blivet/pull/121]
=> Add overrides for the lvm_is_valid_thpool_chunk_size() function

dist/libblockdev.spec.in
The libblockdev python bindings don't really require python. Programs
using libblockdev via the python bindings require python. Remove the
gi.overrides files from autorequires so that the main libblockdev
package can contain all it needs for gobject-introspection bindings
without adding python-abi dependencies.
=> Filter the python files from automatic rpm requires

tests/library_test.py
=> Change the modified sources back in tearDown() method as well.

Makefile.am, docs/libblockdev-docs.xml.in
Makefile.am:
- add separate check target - previously this was repeated in all the test targets
- add coverage targets - makes it possible to use the Python coverage tool to generate reports
- make it possible to test with Python3 - just use variables instead of binary names so it is possible to override them on the command line.
Add description of these new Makefile targets to the docs as well.
=> Makefile updates

tests/crypto_test.py
Otherwise I get this failure:
```
======================================================================
FAIL: test_backup_passphrase (crypto_test.CryptoTestEscrow)
Verify that a backup passphrase can be created for a device
----------------------------------------------------------------------
Traceback (most recent call last):
File "/var/www/html/libblockdev/tests/crypto_test.py", line 369, in test_backup_passphrase
self.assertEquals(passphrase, backup_passphrase)
AssertionError: '\xd1\x84\xd1\x80\xd0\xb0\xd0\xb7\xd0\xb0:' != '0j/l5-bvVJ5-2Nj8R-1QH3x'
```
My terminal uses LANG=bg_BG.utf8 by default
=> tests: use LANG=C in test_backup_passphrase()

Makefile.am
We should have as much of the logic of how the CI tests are run in source
control as possible, so that's what this target is for.  Besides this, jenkins
just runs a "git clean" first.
=> Add a new makefile target that does everything needed for jenkins.

Makefile.am
Otherwise they may be discarded by sudo in some environments.
=> Define env variables for sudo via the env utility

src/plugins/btrfs.c, tests/btrfs_test.py
Example of filesystem which can't be parsed by `bd_btrfs_filesystem_info()`:
```
Label: none  uuid: 5dfd18e3-f676-401a-823a-9b5c6f27e08d
Total devices 1 FS bytes used 112.00KiB
devid    1 size 1.00GiB used 138.38MiB path /dev/sdc1
btrfs-progs v4.1
```
The patch allows the function to read **an empty** filesystem label.
=> BTRFS: fix parsing empty partition label

src/plugins/btrfs.c, tests/btrfs_test.py
Allow libblockdev to read info about filesystems with more complex labels.
This suggestion can't read multi-line labels, though; but is sufficient for any arbitrary one-line label.
=> BTRFS: allow an arbitrary label to be set for a btrfs volume

src/lib/plugin_apis/mdraid.api, src/plugins/mdraid.c, src/plugins/mdraid.h
The superblock size should be calculated from an MD RAID member size not from
the size of the whole array. Make this clear in the bd_md_get_superblock_size()
function's documentation and size parameter name.
=> Better document how MD RAID superblock size should be calculated

Makefile.am, configure.ac, data/Makefile.am, data/conf.d/00-default.cfg, data/conf.d/Makefile.am, dist/libblockdev.spec.in, docs/libblockdev-sections.txt, src/lib/Makefile.am, src/lib/blockdev.c.in, src/lib/plugins.h, tests/library_test.py, tests/plugin_multi_conf.d/00-default.cfg, tests/plugin_multi_conf.d/10-lvm2.cfg, tests/plugin_prio_conf.d/00-default.cfg
These commits add support for having multiple implementations for plugins and configuration files specifying which plugins should be preferred and which should be fallbacks. For the rationale please read the [Design Draft for this feature] (https://gist.github.com/vpodzime/008bf30c7d78079e0036).
=> Multiplugin config support

.gitignore, Makefile.am
Minor change but when I come to think about it we can do better. 
At the moment the report only includes `src/python/gi/overrides/BlockDev.py`. Maybe we can combine coverage.py and gcov to report on the C files as well.
=> Produce coverage report in CI

src/plugins/lvm.c, tests/lvm_test.py
If an LV is added to a VG, no extra meta data is allocated and it doesn't matter
at all if one or more of the VG's PVs are MD RAID devices or whatever, they are
just block devices. In the end we just need to make sure the LV size is rounded
up to the PE size.
Also update the tests accordingly.
=> Fix the calculation of physical space taken by an LV

src/plugins/lvm.c, tests/lvm_test.py
Striped LVs are not created like other non-linear LV types. Instead of 'lvcreate
--type striped...' we need to specify the number of stripes.
Also improve the test for creating LVs with specified types.
=> Fix lvcreate calls for striped LVs

.gitignore, Makefile.am
This PR produces pylint.log and a test-suite-python*.log. These are only the test results without all the build stuff from the console. Easier to read.
=> Produce test execution logs

src/plugins/lvm.c
Otherwise LVM may complain about the size not being a multiple of 512. See
https://bugzilla.redhat.com/show_bug.cgi?id=1224638 for more details.
=> Round size in thpoolcreate() to KiB

Makefile.am
That target pipes stuff to tee, which means the error code that gets
reported is the error code of tee.  Thus if a test fails, we will still
see success and keep going.  The fix is to simply use bash as the shell
and enable pipefail on it.
=> Fix error reporting when running "make test".

Makefile.am, configure.ac, data/conf.d/10-lvm-dbus.cfg, data/conf.d/Makefile.am, dist/libblockdev.spec.in, src/lib/blockdev.c.in, src/lib/plugin_apis/lvm.api, src/plugins/Makefile.am, src/plugins/lvm-dbus.c, src/plugins/lvm.h, src/utils/Makefile.am, src/utils/exec.c, tests/lvm_dbus_tests.py
The LVM plugin utilizing the LVM DBus PoC API. If installed, it tries to load and check that the LVM DBus API is provided. If that fails, the old/original LVM plugin using the ``lvm`` utilities is used instead. For the caller code this is completely transparent, but calling ``bd_get_plugin_soname()`` can be used to determine which plugin actually loaded.
=> LVM DBus plugin

tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/kbd_test.py, tests/library_test.py, tests/loop_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/md_test.py, tests/mpath_test.py, tests/s390_test.py, tests/swap_test.py
Python's unittests have a weird glitch -- the tearDown() method of a test case
is not called always. There are cases (exception in setUp(), exception in the
test?,...) when it's just skipped. However, we need to always clean after
ourselves and that's why need to use the addCleanup() method which adds
callbacks that are called ALWAYS when the test is done (succeeding, failing,
erroring, whatever).
=> Use addCleanup() instead of tearDown() in tests

src/plugins/lvm-dbus.c
The LVM DBus service may be available, but not running. However, we can easily trigger its autostart.
=> Trigger LVM DBus autostart

Makefile.am, configure.ac
Sometimes, it's not desired to fire up the tests when the build is about to complete.
**Usage:**
`./configure --disable-tests && make`
=> Make invocation of tests configurable

src/plugins/lvm-dbus.c
For example if we are not running as root, we may not get introspection data
from services running on the SystemBus or just because the policy says so.
=> Don't expect to always get introspection data from DBus

Makefile.am, tests/library_test.py, tests/md_test.py
We don't really need to run the tests with both Python 2 and Python 3. Also, we don't need to run gtk-doc just to recompile a plugin. And we can try harder to clean after ``mdadm``.
=> Make the tests run faster and a bit better

dist/libblockdev.spec.in, src/plugins/lvm.c
LVM does preliminary checks on the given size and in case it's not a multiple of
512, it exits with an error never reaching the code that would actually round
the given size to usually a multiple of extent size. Let's use KiB ("K" in LVM's
twisted notation) instead.
=> Don't pass sizes in bytes to LVM (#1317373)

configure.ac, src/lib/plugin_apis/btrfs.api.in, src/plugins/btrfs.h.in
For that to start happening we need to define specific constant for the minimum size of a btrfs member device which is (for some reason, page size?) 256 MiB on aarch64. I run the tests manually on our jenkins slave and everything worked just fine.
=> Make tests pass on aarch64

src/lib/plugin_apis/part.api, src/plugins/Makefile.am, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
Not sure how often multiple partition flags are set, but if it happens, it's
better to do it in a single function call with a single commit to disk. This
also brings some atomicity to the operation as if (un)setting one flag fails,
nothing is commited to the disk.
Requested in the issue #81.
=> Add a function for setting multiple partition flags at once

docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/s390.api, src/plugins/s390.c, src/plugins/s390.h
Some pretty isolated and self-explanatory (I hope) changes.
One commit fixes a tiny amount of fall-out from commit b733870 by making sure to pass const parameters to blockdev utility functions.
The other commit adds zFCP functionality. Unfortunately, there is no real way to test these other than manually.
=> Zfcp functionality

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
The second commit adds some extra information to the ``LVMLVdata`` structure returned by the ``lvinfo()`` and ``lvs()`` functions. The existing tests should pass, but some more should probably be added which I'll do later before I push this.
=> Extra LVM info

src/plugins/lvm-dbus.c
We need to use a different interface for cache pools. Let's just try both.
=> Report (meta)data LV name properly for cache pools in lvm-dbus

src/lib/plugin_apis/mpath.api, src/plugins/Makefile.am, src/plugins/mpath.c, src/plugins/mpath.h
It's easier and faster to get the whole list at once instead of asking if a
device is an mpath member for all devices one at a time.
=> Add a function to get all mpath member devices

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, tests/lvm_dbus_tests.py, tests/lvm_test.py
These allow for a multi-step creation of thin/cache pools with much better
control of their data/metadata parts' features.
=> Add functions for creating thin/cache pools from existing LVs

src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/utils/Makefile.am, src/utils/exec.c, src/utils/exec.h
These three patches add the generic framework for progress reporting based on extracting progress information from an exec`ed process or from the LVM DBus API's *Job* objects (doesn't work properly right now, though). Plus a proof-of-concept implementation for the ``pvmove()`` function.
=> Progress reporting generics

src/plugins/lvm.c, tests/lvm_dbus_tests.py
The first one to make sure LVM DBus tests are run whenever possible, the second one reacting on the change of LVM's CLI behavior. Hopefully this will be enough to make tests pass again.
=> Fixes for LVM tests

src/lib/Makefile.am, src/plugins/Makefile.am, src/utils/Makefile.am
When playing around with the library I discovered that I needed to link in libraries which were needed by libblockdev libraries themselves and not my application.  This __underlinking__ is more than just an inconvenience, it creates direct dependencies to libraries that the end application doesn't directly use.  Thus when a new dependent library is released, the end binaries need to be recompiled too, when only the underlying library needed to be re-compiled.
```
gcc -Wall main.c `pkg-config blockdev --cflags --libs`
/usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../lib64/libblockdev.so: undefined reference to `dlopen'
/usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../lib64/libblockdev.so: undefined reference to `dlclose'
/usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../lib64/libblockd …
```
=> Correct underlinking of shared libraries

src/plugins/dm.c
We don't exec any utilities for these actions so they are not covered by the
generic progress reporting code.
=> Add progress reporting to DM RAID (de)activation

src/plugins/kbd.c
When destroying bcache, we cannot try to stop the cache part if there is none
(was detached).
=> Don't try to stop cache part of bcache if there's none

src/plugins/lvm-dbus.c
The type signature for a DBus object path is "o". Now that the LVM DBus API
properly sets types of its accepted and returned values, we can finally safely
use the signature in all expected places.
=> Make sure all object paths are passed and extracted as such

src/plugins/mdraid.c, tests/md_test.py, tests/mdadm_fw_RAID_examine/mdadm
mdadm's API (CLI) is ambiguous and may provide the RAID level as either the
"RAID Level" or "Raid Level" item. Since we store these items in a hashtable,
let's try to lookup both if the first one fails. Another approach would be to
cannonicalize all the items keys when creating the hash table, but that seems
like an overkill for one weird quirk.
=> Try to search for "RAID Level" in mdadm's output (#1379865)

src/plugins/lvm-dbus.c
It's in seconds not milliseconds like the DBus method call timeout.
Resolves: rhbz#1378970
=> Fix the number passed to LVM DBus as a job-creation timeout

docs/libblockdev-sections.txt, scripts/boilerplate_generator.py, src/lib/plugin_apis/Makefile.am, src/plugins/btrfs.c, src/plugins/btrfs.h.in, src/plugins/crypto.c, src/plugins/crypto.h, src/plugins/dm.c, src/plugins/dm.h, src/plugins/fs.c, src/plugins/fs.h, src/plugins/kbd.c, src/plugins/kbd.h, src/plugins/loop.c, src/plugins/loop.h, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/plugins/mdraid.c, src/plugins/mdraid.h, src/plugins/mpath.c, src/plugins/mpath.h, src/plugins/part.c, src/plugins/part.h, src/plugins/s390.c, src/plugins/s390.h, src/plugins/swap.c, src/plugins/swap.h, tests/library_test.py
The first commit makes the check/init/close functions of plugins public and callable if plugins are used as standalone libraries. The rest are just minor fixes and tweaks making things nicer and better.
=> Public check/init/close functions

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h
These are required by storaged and now also provided by the LVM DBus API.
=> storaged extra requirements for LVM plugins

src/lib/plugin_apis/loop.api, src/plugins/loop.c, src/plugins/loop.h, src/python/gi/overrides/BlockDev.py, tests/loop_test.py
storaged supports almost everything that's possible to do as part of setting up
a loop device. In order to be a sufficient backend for storaged we need to
support the same set of features.
We need to reorganize the tests a little bit to make sure that everything is
cleaned up properly in case of failure.
=> Add extra parameters to loop_setup required by storaged

docs/libblockdev-sections.txt, src/lib/plugin_apis/mdraid.api, src/plugins/mdraid.c, src/plugins/mdraid.h, src/python/gi/overrides/BlockDev.py, tests/mdraid_test.py, tests/s390_test.py
The first commit adds features required by storaged from the mdraid plugin. The other removes a function we no longer need for the new 2.0 API.
=> storaged mdadm extra

src/plugins/mdraid.c, tests/mdadm_fw_RAID_examine_migrate/mdadm, tests/mdraid_test.py
If a RAID set is undergoing any operation considered to be a
'migration' - which includes initialization of a new set at any
RAID level that includes redundancy - mdadm --examine will have
lines like this:
RAID Level : 5 <-- 5
Members : 3 <-- 3
Map State : normal <-- uninitialized
At present we don't understand this at all. This is a fairly
minimal fix which just has parse_mdadm_vars notice such lines,
split the 'value' on "<--", and stuff the first value (the one
being migrated *to*, which is usually what we care about, I
think) into the table. We could do something more elaborate
like store both values and make `get_examine_data_from_table`
understand that, but it's more complicated and this should be
all we truly need for now.
=> Handle mdadm --examine output during migration

src/plugins/part.c
We block udev from generating events for the device while we are between
committing changes to disk and informing kernel about the changes. If we close
the file descriptor later, no udev changes are generated either unless we open
is as RDWR. Here's the difference:
RDONLY:
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent
KERNEL[68221.911864] change   /devices/virtual/block/loop0 (block)
KERNEL[68221.913442] change   /devices/virtual/block/loop0 (block)
KERNEL[68221.913794] add      /devices/virtual/block/loop0/loop0p1 (block)
KERNEL[68221.915019] change   /devices/virtual/block/loop0 (block)
KERNEL[68221.915217] change   /devices/virtual/block/loop0/loop0p1 (block)
UDEV  [68221.941293] change …
=> Open the device file as RDWR when committing parts

configure.ac, data/conf.d/00-default.cfg, data/conf.d/10-lvm-dbus.cfg, src/lib/Makefile.am, src/plugins/Makefile.am, src/utils/Makefile.am
This is an incomplatible release breaking the API. We need to make it clear by
bumping the library versions as well as the package version.
=> Bump version numbers to 2.0

src/plugins/mdraid.c, tests/mdraid_test.py
Also update the tests to test this case.
=> Fix md_name_from_node to work with the "/dev/" prefix

dist/libblockdev.spec.in
It clearly requires these packages to be installed because it needs many
utilities from them.
=> Add xfsprogs and dosfstools as dependencies of the fs plugin

src/plugins/mdraid.c, tests/mdadm_extra_name_stuff/mdadm, tests/mdraid_test.py
Sometimes mdadm provides some extra information for the MD RAID's name, e.g.:
biter2:bd_test_md  (local to host biter2)
instead of just:
biter2:bd_test_md
Let's ignore such extra information when gathering the name attribute from both
--examine data and --detail data.
=> Trim the extra info for MD RAID's name

docs/libblockdev-sections.txt, src/lib/plugin_apis/loop.api, src/plugins/loop.c, src/plugins/loop.h, tests/loop_test.py
There are basically two things required by storaged which are not currently provided by the loop plugin:
=> Extra functions for the loop plugin required by storaged

src/plugins/kbd.c, tests/kbd_test.py
Sometimes the /sys/.../register file doesn't exist when we try to write to
it. Let's give it a chance to appear in some sensible time frame. With some luck
the file appears and the bcache device is successfully registered (and then
properly created and set up).
Also enable some of the risky tests that seem to have been failing due to the
issue fixed here.
=> Try harder to register a new bcache device

src/plugins/swap.c, src/plugins/swap.h, tests/swap_test.py
The kernel API for swap (de)activation is very simple and
straightforward. There's no need to fork and exec the swapon/swapoff utilities,
we can use the system calls directly.
=> Reimplement swapon/swapoff functions by using syscalls

configure.ac, src/lib/blockdev.pc.in, src/plugins/kbd.c, src/plugins/kbd.h
When compiling libblockdev, we define macros to make sure bcache support is
compiled in or not. However, when the library is built and we ship the header
files, there's no way to determine if the bcache support is built in or not and
the macros are of course no longer defined. By providing cflags for compiling
things with libblockdev, we can propagate the information if bcache is supported
or not.
=> Make sure bcache functions are correctly provided or not

src/lib/plugin_apis/mdraid.api, src/plugins/mdraid.c, tests/mdraid_test.py
'mdadm --grow' accepts either '/dev/mdXXX' or '/dev/md/name' so
allow using both name (or just node name) and full path from
libblockdev.
=> Allow using both path and raid name in bd_md_set_bitmap_location

src/lib/plugin_apis/mdraid.api, src/plugins/mdraid.c, src/plugins/mdraid.h, src/python/gi/overrides/BlockDev.py, tests/mdraid_test.py
Multiple MDRAID plugin functions expect 'raid name' as input but
mdadm allows more ways of specyfing the raid -- e.g. using the
'/dev/md127' path or using the path with name (e.g. '/dev/md/name')
or just the name or node (e.g. just 'md127').
This change takes user input for these functions and tries to find
the best 'specification' and use it when calling mdadm.
=> Allow specifying raid 'name' in multiple way when calling md functions

docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
A LUKS passphrase can be an arbitrary sequence of bytes including '\0' (0) bytes
which are terminating strings in C. If we take the passphrase argument as
'gchar *', we need it to be '\0'-terminated otherwise we don't know its
length. We need a set of new functions taking the passphrase argument as
'guint8 *' together with its length (gsize) if we want to support arbitrary
sequences of bytes as LUKS passphrases.
Note: this is required by https://github.com/storaged-project/udisks/pull/195
=> Add functions using BLOBs as LUKS passphrases

dist/libblockdev.spec.in, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/library_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py
So that it can be shown to users for confirmation or simply
because the caller code may need to make sure everything fits in
the space available in a VG when creating thin pool.
Resolves: #167
=> Add function for getting recommended thpool metadata size

docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/s390.api, src/plugins/s390.c, src/plugins/s390.h
This will enable blivet to choose a correct disklabel type for an FBA device.
=> Add the bd_s390_dasd_is_fba function to check if DASD is FBA

acinclude.m4, configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am
These commits make *libblockdev* builds modular -- not all plugins have to be built and packaged. And of course not all build dependencies are required if some plugins are not being build. This should make packaging *libblockdev* on other distributions much easier.
=> Modular builds

src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
It may be too small as given by the thin_metadata_size tool which
obviously doesn't guard for too small values.
=> Make sure the returned thpool MD size is valid

src/plugins/mdraid.c, tests/mdraid_test.py
It is possible to call 'mdadm --assemble' using the '/dev/md...'
path so do not try to parse/check given raid specification --
even non-existing path is a valid input for this function.
=> Do not try to parse 'raid_spec' for 'bd_md_activate' (#1439111)

src/plugins/part.c
"ped_partition_get_name" crashes for inactive partitions (like
free space)
=> Do not try to get name for inactive partitions

src/plugins/mdraid.c, tests/mdraid_test.py
The right command is 'mdadm array --fail device --remove device'.
=> Fix mdadm command for removing failed device from an array

src/plugins/fs.c, src/plugins/part.c, tests/crypto_test.py, tests/fs_test.py, tests/kbd_test.py, tests/part_test.py, tests/utils.py
These are the fixes and adaptations of both the code and tests to allow us running tests on CentOS/RHEL 7. The only remaining failing test is the one for getting *zram* stats where the failure is caused by incompatibilities between the 3.10 and almost-vanilla kernels in el7 and Fedora respectively.
Apart from disabling tests related to bcache (which is not available on el7) there are bugs in the el7 versions of ``volume_key`` and ``libparted`` that make it impossible to run some tests properly. Those will be reported.
=> Fixes to make tests passing on CentOS/RHEL 7

configure.ac, src/lib/plugin_apis/btrfs.api, src/plugins/btrfs.h
This reverts commit 37d568d3c286e3d455da54ddd004712a864d9f3d.
It seems to be 128 MiB on aarch64 too now.
=> Revert "Use different BTRFS_MIN_MEMBER_SIZE on aarch64"

tests/btrfs_test.py
Btrfs has different min size limits on Fedora 25.
=> Skip btrfs min size tests on Fedora 25

dist/libblockdev.spec.in, docs/libblockdev-sections.txt, src/plugins/dm.c, src/plugins/mdraid.c, src/plugins/mpath.c, src/plugins/swap.c, src/utils/Makefile.am, src/utils/dev_utils.c, src/utils/dev_utils.h, src/utils/utils.h, tests/utils_test.py
These often come handy. Is the fact that the *utils* library now requires *libudev* a problem? I think it should be fine since that library is required by a number of core system components and the *libblockdv-dm* plugin already requires it too.
=> Add functions for resolving device (symlinks) and getting device symlinks

dist/libblockdev.spec.in, src/plugins/loop.c, tests/loop_test.py
There's no need to fork and exec the 'losetup' utility.
=> Use ioctl() call to teardown loop devices

src/lib/blockdev.c.in, src/utils/extra_arg.c, src/utils/extra_arg.h
Libblockdev initialization and using the extra args (BDExtraArg)
is quite complicated so add some code snippets to demonstrate
usage of this functionality.
=> Add few code exaples to documentation

tests/kbd_test.py
Before trying to remove a zram device, we need it to be fully
setup. However, there's no way to find out when that happens so
just give kernel some more extra time and hope it will be enough.
=> Make sure we give kernel time to fully setup zram device(s)

src/lib/Makefile.am
Only the plugins require those not the library itself.
=> Do not link libraries required by plugins to the GI files

configure.ac
Fixes build failures in cross environments where the tools may be
prefixed with the host triplet, e.g. x86_64-pc-linux-gnu-pkg-config.
=> Fix hardcoded reference to pkg-config

acinclude.m4
Fixes build failures in cross environments where the tools may be
prefixed with the host triplet, e.g. x86_64-pc-linux-gnu-gcc.
=> Fix hardcoded reference to gcc

configure.ac, dist/libblockdev.spec.in, src/lib/Makefile.am
Support for GObject introspection is one of the best features of
libblockdev. However, there are cases when the C API is enough
which means the GI support should be optional. The common GI
macros already support the '--enable/disable-introspection'
option for './configure', we just need to respect it properly.
=> Make GObject introspection optional

tests/lvm_test.py
Otherwise the rest of the cleanup(s) is/are skipped, leaving
garbage in the system for the following tests.
=> Catch and ignore partial failures in LVM tests' cleanups

src/plugins/kbd.c, tests/kbd_test.py
When you create a cached device with a backing device at the same
time you do not need to separately register and attach devices.
This is done by the udev rules.  This fixes an issue where the
code was doing an attach for a device that was already attached.
The bcache sysfs attach kernel entry will return -2 in an unsigned,
which yields 2**32-2 returned to user space.  This will cause an
abort if you are running G_DEBUG=fatal-criticals in glib as
g_io_channel_flush does a g_string_erase of the write buffer for
the number of bytes written, which is ~4G, and we only actually
have a 1K buffer that we wrote 36 bytes of.
Signed-off-by: Tony Asleson <tasleson@redhat.com>
=> kbd.c: Make bd_kbd_bcache_create work without abort

src/plugins/part_err.c
Ignore parted exceptions of type warning and information if parted marks them as ignorable. Fixes #214.
~~I haven't tested this yet \*cough*. Plus I should probably add at least one test case in which a parted warning is ignored. So please don't merge yet.~~
=> Ignore parted warnings if possible

src/plugins/Makefile.am, src/plugins/crypto.c
This is volume_key/libvolume_key.h, not libvolume_key.h.
configure.ac searches for the header in the correct location `volume_key/libvolume_key.h`, and then crypto.c tries to include it as `#include <libvolume_key.h>`, so compilation fails even after installing volume_key.
=> Fixed include for libvolume_key.h

src/plugins/fs.c
The bd_fs_resize function uses the xfs_resize_device
helper function with size in bytes, so instead of
forwarding this to bd_fs_xfs_resize which takes the
size in blocks, it has to be converted correctly
within xfs_resize_device using the block size.
=> Size in bytes for xfs_resize_device

docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h
So that people can use libblockdev to work with their encrypted
devices using TrueCrypt/VeraCrypt.
Resolves: #200 
note: I have only manually tested the functionality because it's practically impossible to create a TrueCrypt/VeraCrypt volume for tests.
=> Add functions for opening/closing TrueCrypt/VeraCrypt volumes

configure.ac, src/utils/exec.c
It supports some nice extra features like declaring variables for
'for' cycles just in/for the cycles. Let's check the change works
by doing exactly that at least in one place (and all future
code).
Please note that '-std=c99' doesn't work for us because we are
obviously using some GNU extensions. So we must use '-std=gnu99'.
=> Compile everything with the C99 standard

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, tests/fs_test.py
The FS plugin functions bd_fs_can_resize/check/repair
can be used to test for installed utility and FS support
before starting the action or exposing it in an UI.
Maybe you can give me feedback on this - I intend to use it in UDisks. It already has a value e.g. because it could be called to see if resize is supported by the generic resize method.
But to make it more meaningful the check_deps() would need to not already fail if e.g. xfs_db is missing. Currently this requires UDisks to depend on xfsprogs and if other filesystems like ntfs would be supported in FS plugin they all would need to be dependencies if check_deps() will remain strict. Through these functions the caller could query for support and there is no need for a hard dependency. But this would be another PR.
=> Query functions for FS resize and repair support

docs/libblockdev-sections.txt, src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
The new function bd_part_resize_part allows to
change the size of a partition and guarantees
that it does not move and has at least the requested
size allocated. It also supports resizing to maximum.
Should I write tests as well or is it anyway better if they are not written by the one writing the code?
=> Add partition resize function

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, tests/fs_test.py
Introduces bd_fs_can_set_label to query for installed
tooling. Adds the generic function bd_fs_set_label to
set the filesystem label of a device.
The test case for XFS fails if a space is contained like "new label" - what's wrong there?
=> Query setting FS label support and generic relabeling

src/plugins/part.c, tests/part_test.py
*Note: This PR was created as an extension of the PR #253 with two extra commits fixing the behavior on RHEL/CentOS7 and making things a bit more strict.*
If the caller of the partition creation and
resize functions is not aware of size reductions
due to alignment it should still be able to give
the theoretical free space as size argument.
This should be possible by a 3 MiB tolerance which
the final partition is allowed to be smaller.
This is to make it easier for an application that should rather use '0' to still be able to pass e.g. the device size to create one big partition.
=> Specify tolerance for partition size

configure.ac, src/plugins/fs.c
We can use a new function "mnt_context_get_excode" to get error
code and error message when (un)mounting a device. This is
available since libmount 2.30
=> Use new libmount function to get (un)mount error message

tests/kbd_test.py
zram module loading and unloading very often causes kernel panics
on the rawhide kernels.
=> Skip zram tests on Rawhide

tests/btrfs_test.py, tests/dm_test.py, tests/kbd_test.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/s390_test.py, tests/swap_test.py, tests/utils.py
We only need to make sure specific utilities are not available in
the tests that require so. Otherwise we are getting many warnings
for missing utilities in the tests.
Resolves: #203
=> Keep most utilities available for tests

scripts/boilerplate_generator.py, tests/library_test.py
Sometimes it's undesirable to do strict dependency checks, especially right at the beginning when the library is being initialized. The dependencies may for example be installed later, right before or after the functionality requiring them is used for the first time.
Resolves: #248 
*Note: this includes a patch from #259 as it makes the ``fake_path()`` context manager more versatile and we are making use of it here*
=> Add a way to disable runtime dependency checks

autogen.sh, src/lib/Makefile.am
Hello,
what do you think about that?
This enables to build with e.g. jhbuild/gnome-continuous. The autogen.sh comes from GNOME Disks and could be improved I guess(?). I also ran into a linking error if all plugins were disabled.
Best regards,
Kai
=> Allow non-source directory builds and no-plugin builds

tests/fs_test.py
Otherwise pvcreate fails if it detects some old signature on the device.
=> Use -ff when creating PVs in FS tests

src/plugins/part.c
Sometimes it magically happens that libparted kills the whole
process trying to create a partition due to the
assert(disk->dev->open_count > 0)
Which should obviously never happen because we are never opening
or closing the device explicitly just by means of
ped_device_get() and ped_device_destroy(). So this is probably a
bug in libparted, but we have no reproducer for it.
Let's just try to make sure the device is opened while we are
trying to commit the new partition table to it.
=> Make sure the device is opened for libparted

tests/btrfs_test.py
btrfs module is not available there.
=> Skip btrfs tests on CentOS 7 aarch64

configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am, src/plugins/kbd.c, tests/kbd_test.py
Bcache stats in sysfs are sometimes wrong or take long time to
get updatedi after bcache creation. This test shouldn't fail just
because bcache is broken -- so instead of comparing stats returned
by "kbd_bcache_status" with some "expected" values, just compare
them from stats we read from sysfs. It isn't our problem if bcache
is broken.
=> Use system values in KbdTestBcacheStatusTest

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, tests/fs_test.py
Hello,
this adds NTFS to the filesystem plugin.
Since I don't know if you have NTFS stuff installed on the CI, I just added these three basic test cases in a second commit which can be left out if not wanted. Resizing always needs the repairing before and afterwards, otherwise even basic things will refuse to run on a dirty-marked device.
=> Support NTFS

src/plugins/part.c
This is needed to fix a regression in Udisks
(https://github.com/storaged-project/udisks/issues/415).
Fixes: #287
=> Support the legacy boot GPT flag

scripts/boilerplate_generator.py, src/plugins/dm.c, src/plugins/fs.c, src/plugins/lvm-dbus.c
Running `covscan` with `--profile=multi` (instead of `errata`) shows some more warnings.
=> More fixes for issues discovered by coverity

tests/fs_test.py, tests/utils.py
So that they are not making results of our tests hard to work
with.
=> Mark unstable tests as such

src/plugins/s390.c
**bd_s390_dasd_is_ldl should be true only for LDL DADSs:**
The format of DASD can be unformatted, CDL or LDL. We should check
only if the format is LDL, otherwise we could detect also unformatted
DASDs as LDL DASDs.
**Fix bd_s390_dasd_format:** 
We need to set argv to point at the device name, otherwise it is NULL.
=> Fixes in the s390 plugin

tests/kbd_test.py
They are quite often failing due to some issues in
kernel/udev/something that is not our business.
=> Mark bcache tests as unstable

src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
libparted has some "custom flags" on GPT and some these "flags"
are actually not flags but GUIDs and unsetting these "flags"
chages previously set GUID.
=> Use only sgdisk to set flags on GPT

src/plugins/fs/ext.c, src/utils/exec.c, src/utils/exec.h, tests/fs_test.py, tests/utils_test.py
These two commits add a progress reporting capabilities for check/repair of ext2/3/4 fs. It utilizes the existing infrastructure including `bd_utils_init_prog_reporting()`. An example of usage is here: https://github.com/jtulak/fd-issue, but it is the same as for any other of the few operations that currently support progress report.
=> Progress for e2fsck

dist/libblockdev.spec.in
It is still called "pygobject3-base" on older Fedoras.
=> Fix python2-gobject-base dependency on Fedora 26 and older

src/plugins/crypto.c, src/plugins/part.c
This patch fixes POSIX compliance by changing all references to "sys/fcntl.h"
to "fcntl.h", and changes the use of the "__PRI64_PREFIX" to the
equivalent "PRIx64".
=> Fix build against musl libc

src/plugins/s390.c
This removes hardcoded binary paths from src/plugins/s390.c.
=> s390: don't hardcode paths, search PATH

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.h
It is possible that calling a function won't return an error
immediately but will return a job object with 'GetError' property
set so we need to check it too.
=> lvm-dbus: Check returned job object for error

acinclude.m4
'=' is correct, '==' may work with some versions of 'test' (or
shells that don't actually use the utility).
Fixes: #333
=> Use '=' instead of '==' to compare using 'test'

configure.ac
We are using some functions that are not available in older
versions.
=> Require at least libndctl 58.4

configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am, src/plugins/crypto.c
This allows compiling libblockdev without volume_key and nss
dependencies using the "--without-escrow" configure option
("BD_CRYPTO_TECH_ESCROW" technology won't be available).
Fixes #322
=> Allow compiling libblockdev crypto plugin without escrow support

src/plugins/crypto.c
When opening a TCRYPT volume, the keyfiles count is off by one.
=> Fix off-by-one error when counting TCRYPT keyfiles

configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am, src/plugins/dm.c, src/plugins/dm.h
This allows compiling libblockdev dm plugin without dmraid support
using the "--without-dmraid" configure option ("BD_DM_TECH_RAID"
technology won't be available).
Fixes: #321
=> Allow compiling libblockdev without libdmraid

src/plugins/fs/ext.c
The ext4 repair function with progress reporting
did pass "-n" which is the read-only mode.
Use same arguments as without progress reporting.
=> Correct arguments for ext4 repair with progress

src/lib/plugin_apis/fs.api, src/plugins/fs/xfs.c, tests/fs_test.py, tests/utils.py
As described in the issue, xfs_db's check command does not scale
for large filesystems, and is not really a debug tool in xfs_db,
not something for general use.
Fixes: GH-344
=> Use xfs_repair instead of xfs_db in bd_fs_xfs_check()

dist/libblockdev.spec.in
VDO plugin dependencies (vdo and kmod-kvdo) are available only
for x86_64 so it doesn't make sense to build the module on other
architectures.
=> Do not build VDO plugin on non-x86_64 architectures

src/plugins/vdo.c
Just a small fix to prevent memory leaks - even though the `yaml_parser_t` structure is allocated on the stack, its members may point to a dynamically allocated memory.
=> vdo: Properly destroy the yaml parser

configure.ac, docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
We need to be able to specify different kdf (e.g. pbkdf2) and
change some default parameters for argon2.
=> Allow specifying extra options for PBKDF when creating LUKS2

tests/lvm_test.py
Creating cache pool with raid1 metadata is broken on CentOS 7
(already fixed in newest LVM).
=> Skip 'test_cache_pool_create_remove' on CentOS 7

src/plugins/Makefile.am
Not having `libbd_utils.la` first is giving me a libtool error during install, presumably as it's picking up the existing version in `/usr/x86_64-pc-linux-gnu/lib`
```
libtool: warning: relinking 'libbd_crypto.la'
libtool: install: (cd /var/tmp/paludis/build/base-libblockdev-2.18-r1/work/libblockdev-2.18/src/plugins; /bin/sh "/var/tmp/paludis/build/base-libblockdev-2.18-r1/work/libblockdev-2.18/libtool"  --tag CC --mode=relink x86_64-pc-linux-gnu-cc -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/include/nss -I/usr/x86_64-pc-linux-gnu/include/nspr -Wall -Wextra -Werror -march=native -O2 -pipe -std=gnu99 -L./../utils/ -version-info 2:0:0 -Wl,--no-undefined -o libbd_crypto.la -rpath /usr/x86_64-pc-linux-gnu/lib …
```
=> Re-order libbd_crypto_la_LIBADD to fix libtool issue

src/python/gi/overrides/BlockDev.py
"dict_keys" is a special type in Python 3, not a list-like object.
Fixes: #373
=> BlockDev.py Convert dictionary keys to list before using them

src/lib/blockdev.pc.in, src/utils/blockdev-utils.pc.in
Just declaring `libdir` and `includedir` in the `pkg-config` header
doesn't do anything; the following section needs to use them.
This fixes build breakages with programs using `libblockdev` installed
with a non-standard prefix.
=> pkg-config: add -L${libdir} and -I${includedir}

src/lib/plugin_apis/Makefile.am
We can't rely on the shebang, because /usr/bin/python may not be
available on all systems. It's better to use python executable path
discovered by the AM_PYTHON_PATH autoconf macro.
=> Use python interpreter explicitly when running boilerplate_generator.py

src/plugins/btrfs.c, src/plugins/check_deps.c, src/plugins/check_deps.h, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/fs.c, src/plugins/fs/common.c, src/plugins/fs/ext.c, src/plugins/fs/generic.c, src/plugins/fs/mount.c, src/plugins/fs/ntfs.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, src/plugins/kbd.c, src/plugins/loop.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/mdraid.c, src/plugins/mpath.c, src/plugins/nvdimm.c, src/plugins/part.c, src/plugins/part_err.c, src/plugins/s390.c, src/plugins/swap.c, src/plugins/vdo.c, src/utils/dev_utils.c, src/utils/dev_utils.h, src/utils/exec.c, src/utils/module.c
Our LICENCE file always was LGPL 2.1, but some of our copyright
"headers" are GPL (probably because of copy pasting the template
from a "wrong" source). This commit fixes this and changes all
the headers to LGPL 2.1.
=> Fix licence headers in sources

docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/vdo.api, src/plugins/vdo.c, src/plugins/vdo.h, tests/vdo_test.py
This exposes statistics of the specified VDO volume. Instead of calling either
`vdostats` or `vdo info` whose output keys are human-readable strings with
no stability guarantees the statistics are actually taken from /sys/kvdo structure
which seems to be reasonably stable.
There are some keys that are computed by the vdo tools from existing values
so those are backported.
The fact that no calls to the vdo tools are involved makes this function suitable
for reuse within potential VDO support integration in the LVM module. Also since
there's no real I/O involved this function should be reasonably fast.
=> vdo: Implement bd_vdo_get_stats()

dist/libblockdev.spec.in
lidmraid is not available on RHEL > 7
=> Build the dm plugin without dmraid support on newer RHEL

scripts/boilerplate_generator.py
These are just internal helpers that should not be exported.
Related: GH-366
=> Mark the function stubs as static

tests/mdraid_test.py
Removing a spare disk from an MD array sometimes fail on Debian.
I was able to reproduce this manually with just mdadm -- `mdadm --remove` succeeds but the `mdadm --detail` says the spare is still in the array. So this is just another example of broken mdadm.
=> Skip MDTestAddRemove on Debian

tests/kbd_test.py
There are four new stats since kernel 4.19. Checking if we read
more than 11 values should be enough to be sure that the file
has the stats we want.
=> Fix how we check zram stats from /sys/block/zram0/stat

src/plugins/Makefile.am
Link against libbd_utils.la before any *_LIBS can change the linker path.
Related: 12b2506d4853e515e9914d5c761b5501df1242fe
Signed-off-by: Dennis Schridde <devurandom@gmx.net>
=> Fix build of plugins by changing linking order

tests/kbd_test.py
The first argument to the 'skip_on' decorator is an iterable of
distos to skip the test on, the second argument is the version.
=> Fix how/where the bcache tests are skipped

src/plugins/part.c, tests/part_test.py
First commit is copied from #272 -- this PR creates a new libfdisk based plugin, but we have decided to slowly rewrite current (libparted based) plugin to libfdisk and completely remove dependency libparted instead. This commit will be removed after #272 is changed and merged.
=> Rewrite 'bd_part_get_disk_spec' and 'bd_part_set_disk_flag' to libfdisk 

misc/Vagrantfile.tmpl
This can speed things up quite a lot in some cases. And the
vagrant VMs for devel/testing are not supposed to be (considered)
persistent.
=> Use unsafe caching for storage for devel/testing VMs

dist/libblockdev.spec.in
I forgot to add this in b6229b845e7cdea022afa23ae49185a20c8adacf
=> Add libblkid-devel as a build dependency for the swap plugin

tests/crypto_test.py
This test sometimes fails because lsblk doesn't have up-to-date
information. We can force blkid to scan the device and not use
udev.
=> crypto_test.py: Use blkid instead of lsblk to check luks label

src/plugins/mpath.c
The macros from linux/kdev_t.h doesn't work for devices with
minor > 255.
Resolves: rhbz#1644825
=> Use major/minor macros from sys/sysmacros.h instead of linux/kdev_t.h

src/plugins/crypto.c, tests/crypto_test.py
CentoOS 7.6 has oder kernel that doesn't support storing keys in kernel keyring. Also older util-linux doesn't fully support LUKS 2.
=> CentOS 7.6 LUKS 2 related fixes

src/plugins/crypto.c, tests/crypto_test.py
'crypt_activate_by_*' returns -EPERM which translates to
'Operation not permitted' which might be confusing.
=> Add custom error code and message for wrong passphrase for open

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py
Method arguments should be passed as a tuple, but this is already
done in 'call_lvm_method'. If we add it here the result will be
a tuple inside a tuple and this causes lvmdbusd to crash.
=> lvm-dbus: Do not pass extra arguments enclosed in a tuple

src/plugins/crypto.h, tests/crypto_test.py
This is what Debian FDE does and what was suggested in the
following research/analysis:
https://www.whonix.org/wiki/Full_Disk_Encryption_and_Encrypted_Images#Protection_Against_Powerful_Adversaries
Fixes: GH-416
=> Use 512bit keys in LUKS by default

docs/libblockdev-sections.txt, src/lib/plugin_apis/nvdimm.api, src/plugins/nvdimm.c, src/plugins/nvdimm.h, tests/nvdimm_test.py, tests/utils.py
Unfortunately 'ndctl_namespace_get_supported_sector_size' needs
an existing namespace to tell us what sector sizes it supports so
we need to hard code the values.
=> New function to get supported sector sizes for NVDIMM namespaces

src/plugins/crypto.c, tests/crypto_test.py
Instead of manually removing the keyslot and adding new a one.
Our old code also doesn't work in FIPS mode.
=> Use existing cryptsetup API for changing keyslot passphrase

tests/utils.py
Targetcli apparently thinks it's completely ok to remove non-existing lun using wrong syntax :)
```
$ sudo targetcli /loopback/%s/luns/lun0 delete
$ echo $?
0
```
=> tests: Fix removing targetcli lun

dist/libblockdev.spec.in
Only mpath plugin needs device-mapper-multipath so the dependency
for fs and part was probably added by accident.
=> Remove device-mapper-multipath dependency from fs and part plugins

tests/fs_test.py, tests/kbd_test.py
Debian now reports version as "10" instead of "testing" for buster.
=> tests: Fix Debian testing "version" for skipping

tests/kbd_test.py
Looks like the bug was backported to stable.
I really need to finish #432 to make skipping tests easier. But for now this is killing our VMs so we need to fix this asap.
=> Skip bcache tests on all Debian versions

src/plugins/part.c, tests/part_test.py
This covers following functions:
```
bd_part_get_part_by_pos
bd_part_get_disk_parts
bd_part_get_disk_free_regions
bd_part_get_best_free_region
```
There are two behaviour changes
- libfdisk ignores free spaces smaller than grain size (usually 1 MiB) and also rounds their start to nearest MiB -- I think this is ok as these are too small to actually create a partition
- parted has two extra partition types: *protected* (I have never seen this one) and *metadata* (2 sectors at the start of the disk and after the extended partition) -- the metadata partitions might be important for the `get_part_by_pos` because these are actually "unusable" parts of the disk and we might want to return a non-freespace "partition" for these. Do you think it would be a good idea to "manually" create part specs …
=> Use libfdisk for functions for getting partitions

tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/fs_test.py, tests/kbd_test.py, tests/library_test.py, tests/loop_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/nvdimm_test.py, tests/overrides_hack.py, tests/overrides_test.py, tests/part_test.py, tests/run_tests.py, tests/s390_test.py, tests/skip.yml, tests/swap_test.py, tests/utils.py, tests/utils_test.py, tests/vdo_test.py
This is a work in progress pull request adding a new way to skip the tests and run only subset(s) of the testsuite.
The goal here is to be able to "categorize" the tests in a way that allows not only to skip slow and/or unstable tests, but also to run only slow and/or unstable tests. This way we can for example create a separate test run that runs only unstable tests to see if something changed or run only some small subset of the tests to quickly check core libblockdev functionality.
Example of the output with skipped slow tests -- https://paste.fedoraproject.org/paste/pCjYWZkNi1gIsGetYcLy7g
Known issues:
- skipped tests are not counted in the result -- this would require to run the tests manually and/or write a custom test runner to replace `unittest.TextTestRunner`
- the `run_tests.py` …
=> Test tags 

src/utils/module.c
This fixes issues with loading modules with dependencies because
'kmod_module_insert_module' does not resolve dependencies.
=> Use 'kmod_module_probe_insert_module' function for loading modules

tests/utils.py
We are insterested only in major version and CPE name contains
minor versions for some distributions like RHEL.
=> Fix parsing distro version from CPE name

tests/run_tests.py
'TextTestRunner' prints all the results to stderr so we should do
the same for the tests we skip manually.
=> Print skipped test "results" to stderr instead of stdout

src/lib/plugin_apis/lvm.api
GObject instrospection doesn't automatically detect types of the
constants and thinks that all are gint, which doesn't work for
LVM_MAX_LV_SIZE because it's bigger than gint64 and should be
guint64.
Unfortunately there is not way to make the constant in GIR arch
dependent, so we are deprecating it, users shoud use the
bd_lvm_get_max_lv_size function instead.
Fixes #462
=> Fix LVM_MAX_LV_SIZE in the GIR file

tests/fs_test.py, tests/skip.yml
And also skip this test case on Debian. On Debian mounting a read
only NTFS device succeeds even if 'rw' option is specified.
On the other hand on Fedora mounting without the 'rw' option fails
instead of mounting the device as read-only. NTFS mounting is just
weird but the test is now written in a way which expects the same
behaviour other filesystems have.
This is not a bug in libblockdev, running mount manually shows the
same inconsistent behaviour.
=> Move the NTFS read-only device test to a separate test case

tests/fs_test.py
It's better to check NTFS tools availability before running mkfs.
=> Fix skipping NTFS read-only test case on systems without NTFS

tests/skip.yml
Some operations with these snapshots lead to a deadlock in LVM,
see https://bugzilla.redhat.com/show_bug.cgi?id=1739080
=> Skip tests for old-style LVM snapshots on recent Fedora

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
Blivet will use this new information to mark exported VGs as protected -- we had some anaconda bugs where installation crashed because user tried to remove an exported VG.
Unfortunately this doesn't work with the DBus plugin. This is already fixed upstream -- https://sourceware.org/git/?p=lvm2.git;a=commit;h=5bdcafff47ee6a2e57e0c57d18cbc36cf1a2973e -- but not yet released.
=> lvm: Add exported information to BDLVMVGdata

configure.ac, src/plugins/crypto.c
This is only for 2.x, we will use cryptsetup function for 3.0, see #471
=> Use 'explicit_bzero' to erase passphrases from key files

dist/libblockdev.spec.in, src/python/gi/overrides/BlockDev.py
This makes working with libblockdev from Python more user friendly.
Before:
-------
```
<BlockDev.PartSpec object at 0x7f1600306600 (BDPartSpec at 0x563e2eca2450)>
```
After:
------
```
BlockDev.PartSpec (BDPartSpec) instance (0x7fbd382e6360)
flags: 0
name: None
path: /dev/vdg2
size: 5046796288
start: 11812208640
type: 0
type_guid: None
```
Fixes #424
=> Add repr and str function to our structs in Python

docs/Makefile.am
Hi!
This is related to #333 and #334. The build would fail at make shortly after entering docs directory.
=> fix build on shells where 'test ==' fails

tests/lvm_dbus_tests.py, tests/lvm_test.py
LVM now adds "_cpool" suffix to attached pools.
=> Fix expected cache pool name with newest LVM

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_test.py
Our current implementation allows to wipe mounted devices by
default. We can't change this behaviour but we want to allow to
control this so we need a new function.
Related: https://github.com/storaged-project/libblockdev/issues/483
=> Add new function 'bd_fs_wipe_force' to control force wipe

Makefile.am
"python -m pylint" should always find the executable for us.
=> Do not hardcode pylint executable name in Makefile

tests/lvm_dbus_tests.py, tests/lvm_test.py
We need to specify exact version of the plugin otherwise the tests
won't work when running against installed version of libblockdev
because we ship the symlink without the version only in the devel
package.
=> Fix LVM plugin so names in tests

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
Also contains two unrelated fixes for issues discovered during writing this.
Note this is technically an ABI break but the LVM VDO changes are not released yet.
=> Add write policy and index size to LVM VDO data

src/plugins/lvm-dbus.c, src/plugins/lvm.c
Too much copy pasting...
Interestingly this failed to compile only in Copr on 32bit Rawhide.
=> Fix unknown index state enum value for LVM VDO

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, tests/lvm_dbus_tests.py, tests/lvm_test.py
Our users expect to be able to manually control compression,
deduplication and VDO index memory size when creating LVM VDO
volumes. This also makes the API consistent with the VDO plugin
API.
=> Add extra parameters for creating LVM VDO volumes

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/Makefile.am, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/plugins/vdo.c, src/plugins/vdo_stats.c, src/plugins/vdo_stats.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
We need to read the stats from `/sys/kvdo`. Code is shared with the original vdo plugin.
=> Add functions to get VDO stats for LVM VDO volumes

tests/lvm_dbus_tests.py, tests/lvm_test.py
The metadata LV symlink is sometimes not removed after removing
a cache pool we created for tests. This is a huge problem for our
CI because other LVM tests will immediately fail when trying to
create the testVG volume group.
The bug was reported to LVM as rhbz#1800475
=> Manually remove symlinks not removed by udev in tests

misc/Vagrantfile
Makes the builds in those VMs faster.
=> Use all CPUs avaiable on host for the Vagrant VMs

src/plugins/fs/common.c, src/plugins/fs/generic.c
We don't need write support for operations like getting uuid or
label and closing the device opened as rw also emits udev change
event.
=> Do not open devices as read-write for read-only fs operations

src/plugins/part.c, tests/part_test.py
We want to remove all preexisting flags in this function, but only
"real" flags for give partition type, we don't want to remove or
reset GUIDs on GPT.
This is the good old parted flags vs. real flags. Some of flags
that parted uses are in fact GUIDs on GPT and we don't want to
touch these, only the real GPT flags which is already covered by
only setting requested flags when calling "set_gpt_flags".
This is expected functionality consistent with the previous parted
based implementation, see:
https://github.com/storaged-project/udisks/issues/418
https://github.com/storaged-project/libblockdev/pull/306
=> Do not remove all "flags" in bd_part_set_part_flags on GPT

src/plugins/part.c, tests/part_test.py
When searching partition by position, libparted adds a special
metadata partition at the start of the extended partition.
libfdisk doesn't do this so we need to add such partition manually
when creating the list of all partitions for functions that search
a partition by its position.
=> Manually add an extended metadata partition to list of partitions

src/utils/exec.c
Default encoding is UTF-8 and this is more strictly enforced in
newest GLib and things like nul bytes are not longer considered
valid.
See also https://github.com/storaged-project/udisks/pull/729 and
https://gitlab.gnome.org/GNOME/glib/merge_requests/967
=> exec: Disable encoding when reading data from stdout/stderr

Makefile.am, tests/run_tests.py, tests/skip.yml, tests/utils.py
This shoudl allow things like running a separate job for unstable tests only -- we are currently ignoring all errors from tests marked as unstable, but there is a big difference between some of them failing and all of them failing which is easy to overlook. I'm planning to have a separate Jenkins job that will run only unstable tests and upload the results as a separate "category" so it will be easier to review.
Please take a look at the new command line options for selecting tags when running tests and let me know it they make sense and are understandable.
(The pdb commit is from #510.)
=> Allow selecting tags when running tests

src/plugins/vdo.c, tests/fs_test.py
Failed unstable tests are now more visible (see #511) so I was able to notice some failures that are not random and should be fixed.
=> Some unstable tests fixes

src/plugins/lvm-dbus.c
We do not use --activate -ay in the cli plugin and the docstring
doesn't mention the auto activation, so we probably shouldn't do
this in the DBus plugin.
----
I don't have a strong opinion about the auto activation, I just want the DBus and CLI plugins to behave the same way, so if you think we should do the activation, I can change the CLI plugin instead.
The best solution would be to add new argument to the function, but that would be an API break, so maybe for 3.0?
=> lvm-dbus: Do not activate LVs during pvscan --cache

tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/vdo_test.py
Just checking for the kvdo module is not enough because often
the kvdo module can't be loaded after kernel update on unstable
distributions.
=> tests: Skip LVM VDO tests if kvdo module cannot be loaded

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/vdo_test.py
I found few issues in the LVM DBus plugin implementation of the LVM VDO support. Mostly functionality not used by UDisks. Hopefully there's not more.
=> lvm-dbus: LVM VDO fixes

src/plugins/fs.c, src/plugins/fs/f2fs.c, src/plugins/fs/vfat.c
Fixes: #515 
There are no tests for this because the `*_check_deps` functions are not in the Python API, I don't know if this is intentional. Should I add these these to the API files so I can test this or should I try to find a different way? @vpodzime
=> Fix checking for tech modes in the filesystem plugin

src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
We currently fail to gather LVM cache stats for cached thinpools
because the pool LV itself is actually not cached, only the
internal data LV is. This change gets the data LV and cache
information for it if user specifies the "public" thinpool LV.
Resolves: rhbz#1832838
-----
I'n not 100 % sure if this is the best approach, we could simply tell our users it's their responsibility to always give us the data LV, but I think it's better to hide these internal LVM details for them where possible and there's no harm in trying to be a little bit smarter in libblockdev.
=> lvm: Fix getting cache stats for cache thinpools

configure.ac
or else we get unpredictable results with shells != /bin/bash like:
```
checking for gobject-introspection... no (disabled, use --enable-introspection to enable)
./configure: 13672: test: xno: unexpected operator
checking for python3... /var/tmp/portage/sys-libs/libblockdev-2.23-r1/temp/python3.8/bin/python3
./configure: 13838: test: x/var/tmp/portage/sys-libs/libblockdev-2.23-r1/temp/python3.8/bin/python3: unexpected operator
```
Reported-by: Matt Whitlock <gentoo@mattwhitlock.name>
Gentoo-bug: https://bugs.gentoo.org/719442
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
=> configure.ac: Avoid bashisms

configure.ac
My preivous PR didn't cover all bashisms. Matt was so kind to provide a patch which removes the remaining bashisms.
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
=> configure.ac: Avoid more bashisms

tests/lvm_dbus_tests.py
Unfortunately the value of the SavingPercent property on DBus is
never updated so we can't use it to check the value from VDO stats.
=> Do not check VDO saving percent value in LVM DBus tests

docs/libblockdev-sections.txt, src/lib/plugin_apis/nvdimm.api, src/plugins/nvdimm.c, src/plugins/nvdimm.h, tests/nvdimm_test.py
A candidate for API change in 3.0.
I blame @vpodzime for not catching this during the code review, definitely not my fault :grin:
=> Fix typo in bd_nvdimm_namepace_get_supported_sector_sizes

configure.ac, dist/libblockdev.spec.in
I don't expect a new 2.x release before 3.0 but it's possible it will happen again so let's just bump master version to 2.99 to be always ahead for the daily builds.
=> Bump version to be always ahead of 2.x-branch

docs/libblockdev-sections.txt, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/lvm-dbus.c, src/utils/exec.c, src/utils/exec.h
Fixes: #366 
This should cover the last private symbols that are public, except for the part-err symbols which will be dealt with in the parted->libfdisk migration.
=> Fix some more private symbols in the API

src/utils/module.c
Lets avoid error messages like "Failed to load the module 'kvdo'
with options '(null)'".
=> module.c: Fix error message when loading module without options

src/utils/exec.c, tests/utils_test.py
This actually fixes two issue. The _utils_exec_and_report_progress
function didn't set the LC_ALL=C environment variable to make sure
we get output in English. And also we shouldn't use setenv in the
GSpawnChildSetupFunc, it's actually example of what not to do in
g_spawn_async documentation. This fix uses g_environ_setenv and
passes the new environment to the g_spawn call.
----------
`bd_utils_exec_and_report_progress` actually never used the `set_c_locale` function to set locale and because I started using it for `bd_utils_exec_and_capture_output` in #452 it is now broken on systems with non-English locale. We are for example not able to get version of tools from util-linux now:
```
g-bd-utils-exec-error-quark: Failed to determine mkswap's version from: mkswap z util-linux 2.35.2
``` …
=> exec: Fix setting locale for util calls

tools/lvm-cache-stats.c
If multiple cached LVs are given to the lvm-cache-stats tool, it
should add a blank line to separate stats for individual LVs to
make the output easier to read.
=> Add blank line between stats of individual LVs in lvm-cache-stats

tests/lvm_dbus_tests.py, tests/lvm_test.py
Default log level is warning so we need to set it to info for
tests that parse info log entries.
=> tests: Properly set log level for LVM tests parsing log entries

tests/lvm_dbus_tests.py, tests/lvm_test.py
I didn't notice the tests are failing on CentOS 7 in #547
=> tests: Fix calling super() in LVM tests with Python 2

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/ext.c, src/plugins/fs/ext.h, src/plugins/fs/ntfs.c, src/plugins/fs/ntfs.h, src/plugins/fs/reiserfs.c, src/plugins/fs/reiserfs.h, src/plugins/fs/vfat.c, src/plugins/fs/vfat.h, src/plugins/fs/xfs.c, src/plugins/fs/xfs.h, tests/fs_test.py
One of the missing filesystem functionality needed by Blivet. Related: #509
=> Add functions to check filesystem label validity

docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/generic.c, src/plugins/fs/nilfs.c, src/plugins/fs/nilfs.h, src/plugins/fs/ntfs.c, src/plugins/fs/reiserfs.c, src/plugins/fs/xfs.c, tests/fs_test.py
This contains only basic functionality for UDisks and Blivet. None of the advanced features of nilfs2 are supported.
Related: #509
First commit is from #554, second commit will be removed after #553 is merged.
Note: `test_ntfs_set_uuid` will fail because the commit adding UUID to NTFS info is not part of this PR. (I didn't want to deal with conflicts in `fs.api` twice. I will of course merge #554 (and #553) first and rebase this.)
=> NILFS2 support

configure.ac, src/plugins/Makefile.am, src/plugins/part.c, tests/part_test.py
Support for creating partitions using libfdisk. This is currently broken because of bug in udev (maybe) -- when creating partition table and a partition directly after that the add event for the partition isn't created.
=> libfdisk: create part

configure.ac
It's needed only for FS plugin, not for crypto or swap.
Added to a wrong condition in 4e96ceebc7dc51a728c80c29a606a6a37269efe7
=> configure: Fix libuuid requirement for FS plugin

src/plugins/dm.c
There is no "UUID" property in UDev we must use the "ID_FS_UUID"
one.
This comparison works only because most DM RAID members don't have
UUID so the check is skipped, but it fails for DDF RAID members
which have a special GUID/UUID in UDev database.
=> dm: Fix comparing DM RAID member devices UUID

tests/skip.yml
The NTFS mount helper randomly hangs.
=> tests: Skip NTFS mount test on Debian testing

tests/nvdimm_test.py
"ndctl list" now outputs the result as a list for single device
and not as dict, see https://github.com/pmem/ndctl/commit/72c46ab194d9987e7b67bba3ab16d020a5a4b10b
=> tests: Fix getting list of NVDIMM devices for tests

src/plugins/part.c, tests/part_test.py
Just few small adjustments in the resize code. Should fix #557 and tests on CentOS 8 (with fdisk 2.32) should no longer fail.
Fixes: #557
=> part: Few resize related fixes

docs/libblockdev-sections.txt, src/plugins/fs/generic.h
Fortunately #518 is not released yet so it's not an API break. I can't believe I missed this. And also can't believe gcc is ok with this.
=> fs: Fix bd_fs_can_get_free_space name in declaration

tests/fs_test.py
The test started failing on latest rawhide, apparently f2fs shrink is still experimental feature.
=> tests: Fix f2fs shrink test

tests/skip.yml
We are no longer running tests on Debian 9 and CentOS/RHEL 7 and
we are also no longer using (lib)parted in the part plugin.
=> tests: Remove some old/obsolete rules to skip tests

tests/mdraid_test.py
This test never worked correctly. It creates array with a spare,
stops the array and then tries to activate it by adding only the
spare to it. The result is a "half active" array that can't be
stopped using its name which means the array is not properly
removed during cleanup and causes other tests to fail.
Basic (de)nominate functionallity is already covered by the
MDTestNominateDenominate test case so this can be safely removed.
=> tests: Remove MDTestNominateDenominateActive test case

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/exfat.c, src/plugins/fs/exfat.h, tests/fs_test.py
The exFAT PR was opened for so long I completely forgot we merged #553 in the meantime and added support for label validity check.
=> fs: Add function to validate exFAT label

src/plugins/fs/ext.c
bd_utils_log_format is not backported to 2.x-branch
=> fs: Fix in ext_repair compile error caused by cherry pick from master

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm.c
There was a discrepancy around struct BDLVMVDOPooldata related functions
between the API file, C header and C source code, likely a typo with
bd_lvm_vdodata_ name prefix. The public API lvm.h that is shipped publicly
defines the correct bd_lvm_vdopooldata_ symbol prefix however any call
to this function results in an unresolved symbol in runtime.
=> lvm: Fix bd_lvm_vdopooldata_* symbols

src/lib/plugin_apis/fs.api, src/plugins/fs/exfat.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/plugins/fs/nilfs.c, src/plugins/fs/ntfs.c, src/plugins/fs/reiserfs.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, src/python/gi/overrides/BlockDev.py, tests/fs_test.py
The idea here is the users will use bd_fs_mkfs with BDFSMkfsOptions
instead of filesystem specific functions like bd_fs_ext4_mkfs
where they need to manually list all the options.
The list of "generic" options in BDFSMkfsOptions is relatively
short but we add more in the future.
--------
This replaces #578. Main difference is `bd_fs_mkfs` can now be also called with extra options, `BDFSMkfsOptions` has a reserve for future expansion and of course all filesystems are covered, not only ext2. I kept the `bd_fs_can_mkfs` the same, with the out parameter for supported options. I'm still not sure if this makes sense, but I plan to rework the whole "filesystem features" feature in the future (near future I hope), so I'll keep this as it is for now. It is consistent with the other "can" functions …
=> fs: Add generic mkfs function with extra options

tests/skip.yml
Overlook from #599 the skip config needs a full "path" to the
test case which changed after moving the filesystem tests to the
separate directory.
=> tests: Fix skipping fs tests after the test split

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/btrfs.c, src/plugins/fs/btrfs.h, src/plugins/fs/generic.c, src/python/gi/overrides/BlockDev.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py
First two commits are from #583 and #585.
The idea here is to provide functions for users that want to use btrfs as a filesystem and not as a volume manager. This implementation also uses only the command line tools so there are no compile time dependencies (as opposed to the btrfs plugin which we plan to rewrite to use libbtrfsutil library, see #552).
Few highlights:
- `resize` and `get_info` functions will fail when called on filesystem that is part of a multidevice btrfs volume. This is indented and we want users to use btrfs plugin for these. Other functions do not check number of btrfs devices and should generally work, but we'll encourage people to not use these on multidevice btrfs volumes.
- Some functions (`resize`, `set_label`...) take moutpoint as an argument and not the …
=> Btrfs support in filesystem plugin

tests/fs_tests/__init__.py
Without this the btrfs test suite won't be run when running all
tests from fs_tests.
=> tests: Include btrfs_test in tests/fs_tests/__init__.py

docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
Blivet needs this for Stratis support (https://github.com/storaged-project/blivet/pull/915). Encrypted Stratis pools must be unlocked using Stratis API and only way to check whether a LUKS device is actually a "Stratis LUKS device" is by checking tokens (Stratis has a special "stratis" type token).
=> crypto: Add function to get information about LUKS2 tokens

src/plugins/lvm-dbus.c
lvm-dbus.c:244:23: error: unused variable 'avail_deps' [-Werror,-Wunused-variable]
=> remove unused variable and fix build with LLVM/clang

configure.ac
Checking header keyutils.h existence and usability...yes
./configure: line 11726: ,: command not found
=> build: Remove stray comma

src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
512 bits should be default only for AES-XTS which needs two keys,
default for other modes must be 256 bits.
resolves: rhbz#1931847
=> crypto: Fix default key size for non XTS ciphers

src/lib/plugin_apis/vdo.api, src/plugins/vdo.c
g_memdup is deprecated and the replacement g_memdup2 is not yet
available so lets just do the copy manually.
-----
We don't use `g_memdup` on master but 3.0 is still far away so we need to fix so 2.x compiles without the deprecation errors.
=> vdo: Do not use g_memdup in bd_vdo_stats_copy

src/plugins/part.c
Breaking the cycle leaves the rest of the elements in the air.
=> part: Fix elements leak in bd_part_get_part_by_pos()

src/lib/plugin_apis/fs.api, src/plugins/fs/vfat.c
Backported from UDisks: udiskslinuxfilesystem.c:handle_set_label()
=> vfat: Add check for invalid characters in bd_fs_vfat_check_label()

src/plugins/fs/exfat.c
"-n" works with both exfat-utils and exfatprogs.
Related: https://github.com/storaged-project/udisks/pull/883
=> fs: Use "-n" for label in bd_fs_exfat_mkfs_options

tests/skip.yml
Testing now identifies itself as "Debian GNU/Linux 11 (bullseye)"
so the tests that should be skipped on testing needs to be skipped
on "11" too.
=> Fix skipping tests on Debian testing

tests/skip.yml
With LVM DBus API the lvconvert job is never finished which means
the test run never finishes in our CI.
=> tests: Temporarily skip test_snapshotcreate_lvorigin_snapshotmerge

tests/fs_test.py, tests/skip.yml
Backport of #633 #634 #635 and #636 to 2.x-branch
=> Misc test fixes backport

tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/xfs_test.py
So XFS now has experimental support for shrinking in `xfs_growfs`. This was not really publicly announced and I'm not sure how stable and safe it is but we definitely need more work before we support it (especially adding some free space variable to `BDFSXfsInfo`) so let's just skip the test for now with newest xfsprogs.
=> Do not check that XFS shrink fails with xfsprogs >= 5.12

src/plugins/lvm-dbus.c, tests/skip.yml
For functions that return two object paths, one of them must be
a valid path -- either the function returns a newly created object
or a valid job, if it return "/", "/" we should report error.
-----
Still not sure why is this happening but `PvCreate` currently returns `("/", "/")` on CentOS 9 which means we are trying to query progress on `/`:
```
[28] Done.
[28] Waiting for job '/' to finish
[28] Job '/' finished
gi.repository.GLib.GError: g-dbus-error-quark: Waiting for 'PvCreate' method of the '/com/redhat/lvmdbus1/Manager' object to finish failed: Failed to get Complete property of the / object: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist (19)
```
=> lvm-dbus: Report error when function returns no object and no job

tests/fs_tests/generic_test.py, tests/fs_tests/xfs_test.py
Support for shrinking was added in xfsprogs 5.12 not 5.1.12
=> tests: Fix checking for XFS shrink support in tests

docs/3.0-api-changes.xml, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/python/gi/overrides/BlockDev.py, tests/fs_tests/generic_test.py
Our current implementation allows to wipe mounted devices by
default, we should let users decide whether they want it or not.
Fixes: #483 
Related #484 and https://github.com/storaged-project/udisks/pull/901
=> Add new argument for bd_fs_wipe/clean to control force wipe

src/utils/exec.c
Glib will rename "g_spawn_check_exit_status()" to "g_spawn_check_wait_status()"
in version 2.69.
Backport of #641
=> exec: Fix deprecated glib function call

src/python/gi/overrides/BlockDev.py, tests/swap_test.py
This fixes exception translation for plugins with multiple
custom exceptions/xrules (currently only swap plugin uses this
functionallity). Currently only the last xrule added to the
ErrorProxy is considered, this fix makes sure all rules are checked
and correct exception is raised.
=> overrides: Fix translating exceptions in ErrorProxy

tests/crypto_test.py
The error paths should also use the tc/bitlk specific functions
not the copied luks ones. Also both bitlocker and truecrypt need
password because we don't support key file for those.
=> tests: Fix copy-paste in CryptoTestTrueCrypt and CryptoTestBitlk

misc/install-test-dependencies.yml, src/python/gi/overrides/Makefile.am, tests/btrfs_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py, tests/kbd_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/nvdimm_test.py, tests/part_test.py, tests/run_tests.py
The distutils Python module is deprecated and will be removed in Python 3.12. We are using it mostly in tests for `LooseVersion` and `find_executable`.
=> Distutils deprecation

tests/part_test.py
Support for setting the swap flag was added to libparted recently.
This was added as a downstream patch on rawhide so we can't simply
check libparted version for the support so removing this check
entirely is the best solution.
=> tests: Do not check that swap flag is not support on DOS table

tests/fs_test.py
With e2fsprogs 1.46.4 we now see less than 90 % of free blocks on
newly created devices in our tests.
=> tests: Lower expected free space on newly created Ext filesystems

tests/fs_test.py, tests/skip.yml
With latest version of ntfs-3g now available in Fedora, mounting
a read only device no longer returns an error, the device is just
mounted as read only with a warning being printed to stdout.
This test was originally added to check that error reporting from
libmount works correnctly with helper programs so it doesn't makes
sense to keep it when mount.ntfs no longer returns an error.
=> tests: Remove test for NTFS read-only mounting

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, tests/library_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/overrides_test.py
LVM 2.03.12 introduces a new config file `/etc/lvm/devices/system.devices`, all devices that LVM should have access to must be specified there (except for `pvcreate` that can work on any device and will add it to the file). The problem for blivet is that it currently heavily uses the `--config devices { filter=[""] }'` device filtering that is no longer supported, the behaviour of the filter is partially replaced by the `--devices` option where we can specify devices for LVM to use (this bypasses the config file).
This is a work in progress change for blivet with changes limited to the CLI plugin (we'll probably need to add the `lvmdevices` command to LVM DBus API, not sure about that yet) and I will probably change it a lot based on the progress of the blivet code for this new "feature".
=> Support for LVM devices file

configure.ac, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
This adds support for create, open and close actions for standalone
integrity devices using cryptsetup.
----- 
I'm creating this as a draft, because I'm still not 100 % sure the API for `integrity_format` and `integrity_open` makes sense and I might change it a bit when working on the blivet part of the integrity support.
=> Add support for creating and activating integrity devices

tests/skip.yml
Something is broken on rawhide kernel and kills our CI so we'll just temporary skip those two tests.
=> tests: Skip NVDIMM enable/disable and reconfigure tests on rawhide

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
This can be disabled either in LVM by a compile time option or
by a lvm.conf option so we should report a specific error for this
case so users can distinguish between the feature not being enabled
and not being supported at all.
=> lvm: Report special error when system.devices file is not enabled

src/plugins/vdo_stats.c
We are currently using "-1" when VDO logical_blocks_used is 0
which doesn't match the LVM logic which returns 100 so to make
both values in vdo_info and vdo_stats we should return 100 too.
-----
Alternatively we could just adjust the test that currently checks that the value we get from `lvs` and our internal calculation of `saving_percent` is the same, but I think that having two different values would be more confusing.
I'm also not sure what and when changed in VDO, because this wasn't an issue before (`logical_blocks_used` had some valid value so we got the same result for both functions). Unfortunately the VDO kernel module as been broken/behind kernel for so long that we don't have a passing build in our CI where VDO tests weren't skipped.
=> vdo_stats: Default to 100 % savings for invalid savings values

src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
This fixes issue where using `BlockDev.lvm_set_global_config("")` will cause all commands to be run with `--config` without parameter, so for example for `pvremove` we will call `pvremove --config /dev/sda`. It doesn't make sense to call lvm with empty config, `--config ""` doesn't replace/remove defaults from `/etc/lvm/lvm.conf` so if user set's it to an empty string we should just ignore it and set the internal variable to `NULL`.
=> Fix setting "empty" global config for LVM commands

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
LVM doesn't need it to create the VDO pool/VDO LV pair so we
shouldn't require it.
Related: https://github.com/storaged-project/udisks/issues/939
=> lvm: Allow using empty name for VDO pool when creating VDO volumes

src/plugins/lvm-dbus.c, src/plugins/lvm.c
"lvmconfig current" doesn't work together with --config even if we
don't override the "use_devicefile" key. "lvmconfig full" seems to
be working in all cases.
----
This is unfortunately hard to test because there isn't a better way to check whether the `use_devicefile` feature is enabled or not (it's a compile time option and is different even with same versions of LVM on different versions of RHEL/CentOS).
=> lvm: Use "lvmconfig full" to get valid config instead of "current"

tests/crypto_test.py
I'm amazed that creating two loop devices backed with a single file and then changing sector size of one of them to 4k actually works, but it probably explains why the test randomly fails when trying change the sector size.
=> tests: Fix creating loop device for CryptoTestLuksSectorSize

src/plugins/vdo_stats.c
The statistics are no longer available in /sys/kvdo, in the latest
version of kvdo we need to use /sys/block/<pool>/vdo/statistics.
Resolves: rhbz#1994220
-----
Backport of #659
=> lvm: Fix reading statistics for VDO pools with VDO 8

dist/libblockdev.spec.in
subpackages. This is a kind of hack to make sure both packages are
always on the same version.
----
The problem is the `/usr/include/blockdev/lvm.h` header file which is "shared" between `libblockdev-lvm-devel` and `libblockdev-lvm-dbus-devel`. But because there is no relation/dependency between those two package, it is possible to upgrade only one of them. Or it actually isn't possible because the upgrade will fail with a file conflict
```
Error: Transaction test error:
file /usr/include/blockdev/lvm.h from install of libblockdev-lvm-dbus-devel-2.25-9.el9.x86_64 conflicts with file from package libblockdev-lvm-devel-2.25-7.el9.x86_64
```
(obviously only if there is a difference in `lmv.h` between the two versions). If we require `libblockdev-utils-devel%{?_isa} = %{version}-%{release}` …
=> spec: Require the same version of utils for lvm-devel and lvm-dbus-devel

tests/lvm_dbus_tests.py, tests/lvm_test.py
The test_lvcreate_type test case randomly fails on slower machines
when trying to remove the newly created mirror and RAID LVs which
is probably caused by the LV still being synced.
Resolves: rhbz#2030647
=> tests: Wait for raid and mirrored LVs to be synced before removing

tests/crypto_test.py
When creating the loop device using libblockdev (which doesn't
support specifying the sector size in bd_loop_setup) the loop
device is not yet ready when we try to change its sector size
with losetup which means the test setup fails.
-----
#680 wasn't enough.
=> tests: Use losetup to create 4k sector size loop device for testing

src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/mount.c, tests/fs_tests/mount_test.py
According to the mount(2) syscall manpage the return code
for an unknown filesystem is ENODEV, not shared with any other
error condition.
=> fs: Return BD_FS_ERROR_NOFS on unknown filesystem

src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/mount.c, tests/fs_test.py
According to the mount(2) syscall manpage the return code
for an unknown filesystem is ENODEV, not shared with any other
error condition.
This necessarily involves return code change from BD_FS_ERROR_FAIL.
(cherry picked from commit 7577eae8a87831ab238b5ff804bb28f64180a812)
=> fs: Return BD_FS_ERROR_UNKNOWN_FS on mounting unknown filesystem

src/plugins/s390.c
=> s390: Remove double fclose in bd_s390_dasd_online (#2045784)

misc/install-test-dependencies.yml
The package is no longer available on Fedora 35 and newer.
=> install-test-dependencies: Do not install reiserfs-utils on Fedora

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py
For LVM VDO pools LVM DBus API initally didn't support enabling
and disabling deduplication and compression so this wasn't part of
the original LVM VDO support.
#704 for 2.x
=> lvm-dbus: Add support for chaning compression and deduplication

tests/skip.yml
Old/unsupported distributions remove, rawhide is now 37.
=> Update skipiing tests in skip.yml

src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme-fabrics.c, tests/nvme_test.py
Those different error messages in the tests look suspicious, unfortunately I have no real nvme device around to test if it was an actual `libnvme` regression or just tweaked ioctl arguments.
=> libnvme-1.0-rc4 adaptations

docs/libblockdev-sections.txt, src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme-fabrics.c, src/plugins/nvme/nvme.h, tests/nvme_test.py
sysfs topology helper function, there might be others like this needed in the future. The actual matching might change a little bit in the future, the API should stay unchanged. This all works on sysfs paths since there might not be a device node created yet (e.g. detached namespace).
=> nvme: Add bd_nvme_find_ctrls_for_ns()

tests/skip.yml
RAID 1 LVs are broken on latest CentOS/RHEL 9, see
https://bugzilla.redhat.com/show_bug.cgi?id=2081624 for details.
=> tests: Skip test_lvcreate_type on CentOS/RHEL 9

tests/skip.yml
Followup for c97126407e62b2b25291773917bbfd0306ea28ef, the issue
affects the DBus plugin too.
=> tests: Skip LVM DBus writecache tests too

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/skip.yml
This exposes the health status etc and allows for repairs.
This is part of supporting LVM2 RAID in Cockpit:
https://github.com/storaged-project/udisks/pull/969
https://github.com/cockpit-project/cockpit/pull/17226
There is a first demo already: https://www.youtube.com/watch?v=86veT8waLZE
Please check the cockpit PR for updates.
=> lvm: Enhancements for LVM2 RAID support

src/plugins/nvme/nvme-op.c, tests/nvme_test.py
Follow-up on 7ef22c5, a forgotten part.
=> nvme: Fix LBA Format data size matching in bd_nvme_format()

tests/part_test.py
Latest libparted now creates all extended partitions as
PARTITION_EXT_LBA with the lba flag enabled by default.
------
This probably isn't the best solution, but I don't really want to deal with parted changes. Lets hope we'll release 3.0 with libfdisk part plugin soon.
=> tests: Fix expected extended partition flags with new parted

configure.ac, src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme-error.c, src/plugins/nvme/nvme-fabrics.c, src/plugins/nvme/nvme-private.h, src/plugins/nvme/nvme.h
The kernel nvme host driver maps errors to standard errno values,
libnvme maps them back to own internal codes and libblockdev does
the mapping once again for GError. The kernel host driver often
spits more information into the kernel log, but that's very
difficult for userspace to catch for the particular call.
Some codes are available only with libnvme >= 1.1
=> nvme: Differentiate fabrics connection error codes

docs/3.0-api-changes.xml, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/python/gi/overrides/BlockDev.py, tests/fs_tests/generic_test.py
When caller (like UDisks) already knows the filesystem type for
the generic function we can avoid the blkid scan.
=> fs: Allow specifying fstype for generic FS functions

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
Pygobject fails to get size of the returned zero terminated array
on 32bit systems. With older versions we get only the first value
from the list and with newer versions we get an abort. The number
of supported PE sizes is constant so we can use the fixed-size
annotation to workaround this issue without changing API.
=> lvm: Fix bd_lvm_get_supported_pe_sizes in Python on 32bit

src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/python/gi/overrides/BlockDev.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/exfat_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/udf_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py
I posting this here to get some feedback, this is third iteration of the API and I'm still not sure if it makes sense.
Users of this API will be both UDisks where some of these values are currently hardcoded in `udiskslinuxfsinfo` and Blivet where we need this in the filesystem related tasks.
Feel free to recommend better names for the "features" and flags, I was always bad at naming things. I'm also not sure if the single "generic" function is enough, maybe we should consider separate functions for the filesystems.
Also I've added test case only for XFS, I'll add test cases for all filesystems in the final version.
=> fs: Add API for querying filesystem "features"

tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/mount_test.py, tests/fs_tests/xfs_test.py
Starting with xfsprogs 5.19 minimal size for XFS is 300 MiB.
=> tests: Create bigger devices for XFS tests

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_tests/generic_test.py
=> Add generic functions to check filesystem label and UUID

src/plugins/fs/generic.c, src/plugins/fs/nilfs.c
Correct one is mkfs.nilfs2, not mkfs.nilfs.
=> fs: Fix nilfs2 mkfs util in BDFSInfo

dist/libblockdev.spec.in
We don't want to deal with utils backward compatibility, especially
now with 3.0 around the corner, and rpminspect is also complaining
about this.
Resolves: rhbz#2116544
=> spec: Require the same version utils from plugins

tests/skip.yml
After latest kernel upgrade the `targetcli` command hangs when trying to remove remove the PV. We should investigate this further (I wasn't able to attach gdb to the process), but for now we need to protect our CI against hanging forever.
=> tests: Temporarily skip LvmTestPartialLVs on rawhide

src/lib/plugin_apis/fs.api, src/plugins/fs/btrfs.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/plugins/fs/nilfs.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, src/python/gi/overrides/BlockDev.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py, tests/utils.py
Fixes: #766 
Two "issues" with this one:
- *NTFS*: I've decided to keep running `mkfs.ntfs` with the `-F` option by default and pretend the option doesn't exist for NTFS. `mkfs.ntfs` will overwrite preexisting filesystems without asking so the `-F` option mostly allows us to format non-partition devices.
- *ext*: The `-F` option is basically no-op for most cases, because running `mke2fs` with closed stdin answers *yes* to the "overwrite" question, but I decided to keep the option here, someone might want to use it for the other use cases.
=> Add a "force" mkfs option for bd_fs_mkfs

.lgtm.yml, configure.ac, dist/libblockdev.spec.in, misc/install-test-dependencies.yml, src/plugins/fs/Makefile.am, src/plugins/fs/ext.c, tests/fs_tests/ext_test.py
Spawning and parsing is more expensive, and dumpe2fs has the annoying
bug that it triggers udev events when the MMP feature is enabled on a
filesystem.
=> fs/ext: Use libext2fs instead of spawning dumpe2fs

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/plugins/fs/vfat.c, src/python/gi/overrides/BlockDev.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/exfat_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/udf_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py
Currectly UDF and VFAT create (sometimes) a partition table on
the device when running mkfs and only VFAT allows controlling this
behaviour.
Fixes: #767
=> fs: Add a mkfs option to disable creating partition table

docs/libblockdev-sections.txt, src/plugins/fs/generic.c, src/utils/extra_arg.c, src/utils/extra_arg.h
A convenient function to free a list of extra arguments.
=> utils: Introduce bd_extra_arg_list_free()

src/plugins/fs/btrfs.c, src/plugins/fs/exfat.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/nilfs.c, src/plugins/fs/ntfs.c, src/plugins/fs/udf.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, tests/fs_tests/generic_test.py
Empty string for label/UUID doesn't make sense with mkfs so we need to skip the extra option.
=> fs: Fix calling bd_fs_mkfs with empty label or UUID

src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme-info.c, src/plugins/nvme/nvme-op.c, src/plugins/nvme/nvme.h, tests/nvme_test.py
The metadata size field was originally intentionally omitted for the libblockdev API, hiding low-level implementation details that seemed unimportant. Turned out that some drives expose several metadata sizes for the same lba data size, leading to seemingly duplicate entries in the list, causing confusion in upper layers. As this is used for namespace formatting that is a destructive operation, it's wiser to expose this detail to higher levels after all.
=> nvme: Extend BDNVMELBAFormat with metadata_size

dist/libblockdev.spec.in
Mote fixes not covered in #782. We should probably run rpminspect in our CI to avoid these issues in the future.
=> Fix spec issues found by rpminspect

src/plugins/nvme/nvme-fabrics.c, tests/nvme_test.py
This is more sane regarding to memory ownership and the scanned topology tree.
=> nvme: Rework the disconnect device topology crawl

dist/libblockdev.spec.in
Without obsoleting the subpackages upgrading to the latest build won't work without "--best --allowerasing".
=> spec: Obsolte the kbd and kbd-devel subpackages

tests/part_test.py, tests/utils.py
This covers only the tests that deal with the none/minimal/optimal alignment testing, we don't really need to run all the tests twice (different sector size shouldn't affect partition types or GUIDs for example).
Fixes: #726
=> part: Add tests with 4k sector devices

docs/3.0-api-changes.xml, docs/libblockdev-sections.txt, src/lib/plugin_apis/loop.api, src/plugins/loop.c, src/plugins/loop.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py, tests/loop_test.py
New argument for `bd_loop_setup` and a new function to get information about loop devices. UDisks needs to be adjusted to the new API before merging this.
Fixes: #685
=> loop plugin API changes

configure.ac, src/lib/plugin_apis/Makefile.am
=> Drop skip_patterns from configure.ac and plugin_apis/Makefile.am

docs/3.0-api-changes.xml, docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
Users should use bd_crypto_luks_info instead.
Separated from #614 so we can merge it without API change.
=> crypto: Remove bd_crypto_luks_uuid function

src/plugins/nvme/nvme-info.c, tests/nvme_test.py
Use Namespace Identification Descriptor list (CNS 03h) data when available and NVM Command Set Identify Namespace Data Structure (CNS 00h) as a fallback.
Also, if the CNS 00h EUI64 or NGUID fields equal to zero, return NULL instead of zeroes:
"If the controller is not able to provide a ... identifier in this field,
then this field shall be cleared to 0h."
=> nvme: Fix namespace identifiers

src/plugins/btrfs.c
With latest btrfs-progs the "otime" value for snapshots can be empty so we need to adjust our regex for parsing the subvolume information.
With btrfs 6.1:
ID 256 ...level 5 otime - path snap1
With btrfs 5.18:
ID 256 ... level 5 otime 2023-01-04 14:11:41 path snap1
=> btrfs: Fix parsing snapshot info without valid otime

src/plugins/fs/f2fs.c, tests/fs_tests/f2fs_test.py, tests/fs_tests/generic_test.py
New version of #831 I wasn't able to convince regex to make the sector size optional, so more traditional parsing is it.
=> fs: Fix parsing F2FS info from dump.f2fs >= 1.15 output

dist/libblockdev.spec.in
We don't need the dmraid package which provides the dmraid binary and systemd services, the library is provided by dmraid-libs.
=> spec: Remove dependency on dmraid

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/exfat.c, src/plugins/fs/exfat.h, src/plugins/fs/generic.c, tests/fs_test.py
It looks like master is brewing for a 3.x release, with API changes and further changes required in downstream projects, and 2.28 is the last stable release. Since I wanted to have exFAT support without waiting for the upcoming release, I've back-ported a patch to a branch based on 2.28-1.
=> Backport exFAT support on top of 2.28 

tests/skip.yml
This reverts commit d5e989527d80c1176dcbddcd1140c08de1037a05.
The DDF tests now work with the latest rawhide kernel.
=> Revert "tests: Skip DDF RAID tests on rawhide"

src/python/gi/overrides/BlockDev.py, tests/dm_test.py
GI creates wrong member names for enums with just one member, so after removing the RAID technology we get DMTech.DM_TECH_MAP instead of DMTech.MAP.
=> Fix BlockDev.DMTech enum after removing DM RAID support

src/plugins/fs/exfat.c, tests/fs_tests/exfat_test.py
The exFAT volume label is a UTF-16LE string with a maximum size of 22 bytes.
Fixes: #848
=> fs: Improve the exFAT label checks

src/utils/exec.c
Also unset the LANGUAGE variable so it doesn't override the default language (https://sourceware.org/bugzilla/show_bug.cgi?id=16621).
This allows passing a UTF-8 label to mkfs.exfat.
`C.UTF-8` is available since glibc 2.35, and many major distros have supported it downstream for years. However if for some reason `C.UTF-8` is not available then the child's `setlocale()` call will fail and remain with the default (`C`) locale.
Fixes #846
=> Run external programs with the C.UTF-8 locale

dist/libblockdev.spec.in
The dmraid support is no longer needed: blivet (the only user of the API) dropped dmraid support in F38.
=> spec: Stop building dm plugin with dmraid support on Fedora >= 38

tests/skip.yml
This is already fixed in latest LVM in CentOS 9, but the fix didn't make it to 8.
=> tests: Skip lvm_dbus_tests.LvmTestLVcreateRemove on CentOS 8

src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
Fixes: #841 
This should be a relatively safe change -- we add the `--fs ignore` option only for inactive LVs basically restoring the old LVM behaviour.
=> Allow resizing of inactive LVs with latest LVM

dist/libblockdev.spec.in
This was originally added in d617ba370d2df5dad4a1070aaaf751bba46301c5 but we don't really want to depend on the runtime dependencies and definitely not in the devel package. Libblockdev users needs to deal with the dependencies themselves and use the dependency checks in libblockdev to check for runtime dependencies.
=> spec: Remove dependency on dosfstools and xfsprogs from fs-devel

.github/workflows/udisks-build.yml, misc/ci.Dockerfile
The idea is to make sure that changes (especially API changes for the upcoming 3.0 release) won't break UDisks.
=> ci: Add a GH actions job to build UDisks on PRs

.packit.yaml
By default Packit uses the latest tag which doesn't work for the master branch of libblockdev where the working version 2.99.
=> ci: Add custom version command for Packit

tests/utils.py
It's better to fail with an error that run the test case that expects $PATH to be set to a specific (possibly nonexisting) path.
=> tests: Make sure the "fake" PATH for tests exists

src/plugins/fs/generic.c, src/plugins/fs/xfs.c, tests/fs_tests/xfs_test.py
It's not necessary and potentially interferes with other activities on the system.
(For example, when Cockpit is open while a new Stratis snapshot is created, there will be a well timed request to UDisks2 that ultimately mounts the new snapshot filesystem to get its size, right when Stratis runs xfs_db to change the UUID, which will fail because it is unexpectedly mounted.  Amazingly narrow race, but it happens.)
=> fs: Don't require XFS filesystem to be mounted when getting info

tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/skip.yml
The issue we were fixing in #855 actually happens only when shrinking the LV, so the test actually didn't test anything.
=> tests: Fix test for inactive LV resize

src/plugins/fs/xfs.c
Running xfs_infor for a device that is not mounted ultimately executes "xfs_db -c info". Unfortunately, xfs_db opens the device read-write by default. This results in a udev event.
The udev event in turn might result in another call to xfs_info via UDisks2 and Cockpit, which conspire the requests the size of a filesystem for each uevent on it.
Luckily, xfs_db can be told to open the device read-only, with the "-r" option.
=> fs/xfs: Open device read-only for xfs_info

src/python/gi/overrides/BlockDev.py
See 73f1b2a2c812575155e6e1329ee27214f25e41d4 for details. This was intended to fix issue where GI creates "wrong" API for enums with only one member, but we need to keep this backwards compatible for now to not break Blivet.
=> Make changes to Python override enums backwards compatible

src/python/gi/overrides/BlockDev.py
See 73f1b2a2c812575155e6e1329ee27214f25e41d4 for details.
----
One more enum to fix. This one also keeps the change backward compatible, see #875 for details.
=> Fix LoopTech enum in Python overrides

src/plugins/fs/nilfs.c
Setting UUID for ntfs.nilfs2 is not supported.
Fixes: #885
=> fs: Remove UUID option from bd_fs_nilfs2_mkfs_options

tests/skip.yml
The required version of libnvme is not available on CentOS/RHEL 8.
=> tests: Skip NVMe tests on CentOS/RHEL 8

docs/3.0-api-changes.xml, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, tests/lvm_dbus_tests.py, tests/lvm_test.py
Needed by the new blivet feature to support shared LVM setups.
=> lvm: Add 'shared' parameter to lvm_lvactivate

tests/skip.yml
ext4 cannot be checked when mounted with latest e2fsprogs on rawhide. See https://bugzilla.redhat.com/show_bug.cgi?id=2211420
=> tests: Skip test_ext4_check on rawhide

src/plugins/s390.c
Our Fedora builds are failing on this on s390x.
-----
I really need to add an s390x cross compilation to our CI...
=> s390: Do not try to close an unopened stream

src/python/gi/overrides/BlockDev.py
I've added these functions and constants to keep the Python API backward compatible for now, but we want to remove these before 3.0 release. This PR is here so we don't forget.
=> WIP: Remove workarounds for 3.0 API backwards compatibility 

docs/3.0-api-changes.xml, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/ntfs.c, src/plugins/fs/ntfs.h, src/plugins/fs/xfs.c, src/plugins/fs/xfs.h, src/python/gi/overrides/BlockDev.py
bd_fs_xfs_check and bd_fs_ntfs_check and repair didn't allow extra options
Fixes: #475
=> fs: Allow specifying extra options to all check/repair functions

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, tests/fs_tests/ext_test.py, tests/skip.yml
No functional change, some filesystems may support online consistency check but its reporting is rather unclear and will likely be handled by a separate function.
=> fs: Clarify mounted fs scenario for check/repair

src/plugins/vdo_stats.c
I have no idea where this came from, but we don't need (and never did) libparted in vdo_stats.
Fixes: #916
=> vdo_stats: Remove unused libparted include

src/plugins/fs/generic.h, src/plugins/loop.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h
=> Fix exported privated symbols and missing declarations

src/plugins/nvme/nvme-private.h
This should fix some of the lingering symbols reported in #918
=> nvme: Mark private symbols as hidden

src/plugins/loop.c
It can happen that linux header linux/loop.h doesn't include LOOP_SET_BLOCK_SIZE definition, so let's define it locally in such case.
=> loop: define LOOP_SET_BLOCK_SIZE is not defined

configure.ac
Similar to libbytesize, bail out before generating target Makefiles.
=> build: Exit before AC_OUTPUT on error

src/plugins/fs/generic.c, src/plugins/fs/ntfs.c, tests/fs_tests/ntfs_test.py, tests/utils.py
ntfscluster can take as much as 45s to complete on a USB key.
Use ntfsinfo to get size information instead of ntfscluster, ntfsinfo is near instantanous (177ms instead of 45s on the same USB key).
Fixes: #934
=> Use ntfsinfo instead of ntfscluster for faster bd_fs_ntfs_get_info

src/lib/Makefile.am, src/plugins/Makefile.am, src/plugins/fs/Makefile.am, src/plugins/nvme/Makefile.am
While this approach doesn't cover every exported symbol (for that we should probably look into a version script), it at least catches the most common mistakes like in https://github.com/storaged-project/libblockdev/issues/918#issuecomment-1620489927
=> Restrict list of exported symbols via -export-symbols-regex

docs/Makefile.am
Shamelessly picked up from Gentoo Portage:
bash is fine with "test . == ." but e.g. dash fails on not having the two dots quoted as strings.
https://gitweb.gentoo.org/repo/gentoo.git/commit/sys-libs/libblockdev?id=4d0304347f57f44cb1ba4f015aad75ca12e1596a
=> docs: Fix test quotation

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c
Related: https://github.com/storaged-project/udisks/pull/1146
=> fs: Use read-only mount where possible for generic FS functions

src/lib/blockdev.c.in
In preparation for the library going config-less (with builtin config only) let's lower severity of the missing config dir error, reported on udisksd startup:
** (udisksd:31627): WARNING **: 16:16:26.927: Failed to load config files: Failed to get contents of the config dir (/etc/libblockdev/3/conf.d/)Error opening directory ?/etc/libblockdev/3/conf.d/?: No such file or directory. Using the built-in config
=> lib: Silence the missing DEFAULT_CONF_DIR_PATH

tests/crypto_test.py, tests/swap_test.py, tests/utils_test.py
assertRaisesRegexp and assertEquals were deprecated for some time and are no longer available in Python 3.12.
=> tests: Replace deprecated unittest assert calls

src/plugins/nvme/nvme-info.c
Certain drives tend to return more data than expected resulting in stack corruption. Use an interim buffer large enough to handle the excess bytes.
https://github.com/storaged-project/udisks/issues/1152
https://github.com/linux-nvme/libnvme/issues/684
----
This is a dirty workaround until a proper fix is implemented either in libnvme or in the kernel.
=> nvme: Use interim buffer for nvme_get_log_sanitize()

src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
We can't use ord to convert the Python string to the byte array expected, with ord we'd support only ASCII passphrases and we want to support all unicode characters.
=> crypto: Correctly convert passphrases from Python to C

dist/libblockdev.spec.in
We stopped building the VDO plugin in Fedora 34 but never made it obsolete and it is now breaking upgrades.
Resolves: rhbz#2237477
=> spec: Obsolete vdo plugin packages

dist/libblockdev.spec.in
Pointed out during testing of fix for rhbz#2237477. Not critical, but it makes more sense for the devel subpackage to obsolete the removed devel subpackages.
=> spec: Move obsoleted devel subpackages to libblockdev-devel

src/plugins/check_deps.c, src/plugins/fs/btrfs.c
GLib provides nice automatic cleanup macros https://docs.gtk.org/glib/auto-cleanup.html
I'd be happy to convert more of the codebase to it, if this is a desired change.
=> Prefer using g_autofree

src/plugins/part.c
We don't need to open the device read-write for functions like bd_part_get_disk_spec.
Fixes: #961
=> part: Do not open disk read-write for read only operations

src/plugins/fs/ntfs.c
We don't currently support getting progress in bd_fs_ntfs_resize so we should tell ntfsresize to not print it.
Fixes: #963
=> fs: Disable progress for ntfsresize

.packit.yaml
With 3.0 being released and available in Fedora rawhide and 39 we can now have builds done by Packit for new upstream releases.
=> packit: Add configuration for downstream builds

src/plugins/nvme/nvme-info.c, src/plugins/nvme/nvme-op.c, src/plugins/nvme/nvme-private.h
Make sure to provide pagesize-aligned and large enough buffer for ioctls that may involve DMA buffer mapping.
=> nvme: Rework memory allocation for device ioctls

scripts/boilerplate_generator.py, src/plugins/lvm-dbus.c, src/utils/logging.c
One more `g_critical` not converted to our logging function and small change for debug logging.
Related: https://github.com/linux-system-roles/storage/issues/382
=> Two logging related fixes

tests/library_test.py
The tests in PluginsTestCase recompile the library and if this step fails the test case can fail with an unexpected error that is hard to debug so we should just fail early with some reasonable message instead.
Fixes: #944
=> tests: Fail early when recompilation fails in library_test

tests/utils_test.py
These escapes are not meant for Python so we just need to mark the string as regular expresion so Python ignores escape characters in it.
=> tests: Fix "invalid escape sequence '\#'" warning from Python 3.12

.packit.yaml
We can't run ./configure for some jobs in Packit, but we don't really need to -- we can replace the constants manually with sed, because for the Packit builds, we always want to build the entire project.
Fixes: #975
=> ci: Manually prepare spec file for Packit

docs/libblockdev-sections.txt, src/lib/plugins.c, src/lib/plugins.h, src/python/gi/overrides/BlockDev.py, tests/library_test.py, tests/lvm_dbus_tests.py
Starting with Python 3.12 we got some weird complains when setting attributes of BlockDev.PluginSpec in plugin_specs_from_names, it's better to add a fully working constructor to create the struct correctly from the Python overrides.
=> Add BDPluginSpec constructor and use it in plugin_specs_from_names

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/f2fs.c, src/plugins/fs/f2fs.h, src/plugins/fs/generic.c, tests/fs_tests/f2fs_test.py
F2FS doesn't support changing the label for existing filesystems but we still want to be able to check the format when using a custom label for mkfs.
=> fs: Add a function to check label format for F2FS

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_tests/generic_test.py
We don't have a generic function to get filesystem info, but it would still be usefull to be able to easily query whether the functionality is available or not. This is similar to the existing can_get_size and can_get_free_space functions, but these can have some other limits in them (e.g. XFS not having the free space information) that can make a difference between "I can query this FS" and "I can get size/free space of this FS".
=> fs: Add a generic function to check for fs info availability

src/plugins/fs/vfat.c, tests/fs_tests/generic_test.py
We allow using UUID with dash in the middle for VFAT in both check and set_uuid so we should allow it also with the generic mkfs calls.
=> fs: Fix allowed UUID for generic mkfs with VFAT

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/ext.c, src/plugins/fs/ext.h, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/plugins/fs/ntfs.c, src/plugins/fs/ntfs.h, tests/fs_tests/ext_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/ntfs_test.py
For NTFS and Ext we can get a filesystem minimum size estimate using the resize tools. Blivet is currently using this to get filesystem min size for resize and the resize tools return slightly different number than what we get from the dump/info tools.
=> fs: Add support for getting filesystem min size for NTFS and Ext

tests/skip.yml
Debian 12 has libnvme 1.3 and latest LVM is now available on C9S.
=> tests: Remove some obsolete rules to skip tests

configure.ac, src/lib/plugin_apis/nvdimm.api, src/plugins/nvdimm.c
The technology is not used and Anaconda (only user of the plugin) will remove NVDIMM support in the next release.
=> Mark NVDIMM plugin as deprecated since 3.1

src/plugins/part.c
fdisk_partition_get_type returns a pointer to a static table so we shouldn't free it. fdisk_unref_parttype should against this but we see some double free crashes that could be caused by this.
Related: https://github.com/storaged-project/udisks/issues/1208
=> part: Fix potential double free when getting parttype

tests/lvm_test.py
Follow up for #973, I forgot to fix the BDPluginSpec construction for LVM DBus test cases.
=> tests: Use BDPluginSpec constructor in LVM DBus plugin tests

src/python/gi/overrides/BlockDev.py
Python's deepcopy by default tries to use pickle which doesn't work on our structs, where possible we should use our C copy constructor.
The deepcopy functionality is used by Anaconda to copy Blivet devicetree which now includes filesystem information provided by libblockdev.
Related: https://github.com/rhinstaller/kickstart-tests/issues/1025
=> python: Add a deepcopy function to our structs

src/plugins/fs/common.c, src/plugins/fs/common.h, src/plugins/fs/generic.c, src/plugins/fs/udf.c
Simply by including a verbose strerror() representation. I find it useful in some cases.
=> fs: Report reason for open() and ioctl() failures

tests/btrfs_test.py
Latest btrfs-progs return 0 for some subvolume actions that return an error, we'll skip these checks on 6.6.3 for now.
Fixes: #993
=> tests: Skip some checks for btrfs errors with btrfs-progs 6.6.3

src/plugins/btrfs.c, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/fs/btrfs.c, src/plugins/fs/exfat.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/fs/nilfs.c, src/plugins/fs/ntfs.c, src/plugins/fs/udf.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, src/plugins/loop.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/mdraid.c, src/plugins/nvdimm.c, src/plugins/part.c, src/plugins/swap.c, src/utils/exec.c, src/utils/module.c
Let's move UNUSED defition to avoid redundancy.
=> Move UNUSED definition to common header utils.h

tests/dm_test.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/utils_test.py
`pvremove` doesn't remove the devices file entry so we need to do that manually in the tests.
=> LVM devices file fixes

tests/dm_test.py, tests/fs_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/utils_test.py
We do not support LVM devices file on 2.x so we want to completely disable it when running tests. We unfortunately need to disable LVM DBus tests when the device exists because we cannot disable the device file usage in LVM DbusD.
=> Disable LVM devices config file when running tests

tests/fs_test.py, tests/skip.yml
See https://bugzilla.redhat.com/show_bug.cgi?id=2211420
Backport of #907 to 2.x branch
=> tests: Remove ext fs_check tests on mounted filesystem

src/plugins/btrfs.c, tests/btrfs_test.py
Depending on the given mountpoint listing subvolumes returns different pathnames. The pathnames are returned sort of relative to the provided mountpoint. For example listing with `/` as mountpoint can return:
['root', 'home', 'home/foo', 'foo']
While giving `/home` it returns:
['root', 'home', 'root/foo', 'foo']
This gives issues for Cockpit as we want to give users a consistent listing of their subvolumes and UDisks always uses the first MountPoint to look up the subvolumes so Cockpit would either have to figure out how that is relative to the given MountPoint or show inconsistent subvolumes.
---
Some notes for a future situation with `libbtrfsutil` as I don't want to break the API again, independent of mountpoint this returns the same subvolumes:
```
In [12]: [path for (path,info) in …
```
=> btrfs: make btrfs subvolume listing consistent

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
"u" is UINT32, we need to use "t" for UINT64
=> lvm-dbus: Fix passing size for pvresize over DBus

.packit.yaml, NEWS.rst, configure.ac, dist/libblockdev.spec.in
We did a new release from the 3.1.x branch so we need to bump the version here as well to make sure the daily builds are ahead of Fedora.
=> Bump version to 3.1.1

.packit.yaml
We need to bump the release in the SPEC template so it's not overwritten by the autogen call later.
=> ci: Fix bumping release for Packit builds

tests/fs_tests/fs_test.py
We need to be able to mount the filesystems for most of the tests so it makes sense to just skip the test if we have the userspace tools but not the kernel module needed for mounting.
=> tests: Skip filesystem tests if kernel module is not available

tools/Makefile.am
LLD is strict about specifying link dependencies and it complains about libuuid not being provided in LDFLAGS when linking tool binaries.
See https://bugs.gentoo.org/910487
Fixes: #1020
=> build: Fix linking with LLD

src/python/gi/overrides/BlockDev.py
=> Fix pylint possibly-used-before-assignment warning in BlockDev.py

src/utils/module.c, tests/utils_test.py
We want to return true for ext2/3 which are now supported by ext4 module.
=> utils: Check also for aliases in bd_utils_have_kernel_module

src/plugins/fs/Makefile.am
There are some unused parameters in the libext2fs header which together with Wall and Werror means the plugin compilation fails. As a workaround we'll disable the unused-parameter warning for now.
Fixes: #1026
=> fs: Ignore unused-parameter warning in the FS plugin

.github/workflows/blivet-tests.yml, .github/workflows/codeql-analysis.yml, .github/workflows/compilation.yml, .github/workflows/udisks-build.yml, misc/install-test-dependencies.yml
The latest LTS is now available and it has some new compilers available and also the latest libnvme we need to compile the NVMe plugin.
=> ci: Use Ubuntu 24.04 in GitHub actions

src/plugins/fs/Makefile.am
Follow-up for #1028, we still want to show the warning and not completely supress it.
=> fs: Fix ignoring errors from libext2fs

tools/lvm-cache-stats.c
It's a nice helper number for comparison with read and write hit ratios.
=> Add cache size ratio to the output of lvm-cache-stats

.github/dependabot.yml
Dependabot should automatically bump the required versions of GH actions so we don't need to do that manually. I tested this in libbytesize and it seems to be working fine, see https://github.com/storaged-project/libbytesize/pull/146
=> infra: Add dependabot to automatically update GH actions

.packit.yaml, configure.ac, dist/libblockdev.spec.in, misc/install-test-dependencies.yml, src/lib/plugin_apis/lvm.api, src/plugins/Makefile.am, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/vdo_stats.c, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/skip.yml
Few changes we need in order to support VDO with the latest upstream 6.9 kernel. The biggest change is renaming of the module (`kvdo` → `dm-vdo`) and deprecation of the `/sys/kvdo` API.
=> Upstream kernel VDO support

src/plugins/nvme/nvme-info.c
This should not happen in practice when the NVMe spec is thoroughly followed.
=> nvme: Fix potential memory leak

src/plugins/crypto.c, tests/crypto_test.py
We want to show a nice error early when user tries to use a name that is not valid instead of failing with a generic error code during activate.
=> crypto: Show error when trying using an invalid DM name

src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
Unfortunately fdisk doesn't provide API to translate between the GUID and the "name" directly, we can only get it for existing partitions.
Related: https://github.com/storaged-project/blivet/issues/1258
=> part: Add human readable partition type to BDPartSpec

tests/skip.yml
The fixed version of exfatprogs is now available on all supported Fedora releases.
=> tests: No longer need to skip exfat UUID tests on Fedora

configure.ac, docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
Support for OPAL self-encrypting drives using the latest cryptsetup feature that allows combining LUKS and SED OPAL drives.
Marking as a draft for now, I don't plan to do much changes but I might change some smaller things based on the blivet and anaconda support.
=> LUKS OPAL support

plans/blivet.fmf, plans/tests.fmf, plans/udisks.fmf
Testing farm sets priority of their repositories to 9 which means the repo is prioritized over all other repositories including our Copr repo with daily builds preventing the latest libblockdev from being installed in the reverse dependency test.
=> ci: Remove priority from Testing farm repositories

tests/skip.yml
VDO userspace tools are now available on C10S, but are not yet available on Debian where the kernel module is now available.
=> tests: Fix skipping VDO tests on Debian and CentOS 10

src/lib/plugin_apis/crypto.api
The convention is to name the macros PREFIX_TYPE_ and we adhere to it with other types so we should do that here as well.
=> crypto: Fix GType macro for crypto context

.github/workflows/spelling.yml
This uses codespell and spellintian.
=> ci: Add a simple GH action to run spelling tools on our code

README.md
SMART and SED OPAL were added in 3.2 and NVDIMM is deprecated since 3.1.
=> README: Update supported technologies

.github/workflows/codeql-analysis.yml, misc/install-test-dependencies.yml, tests/skip.yml
The VDO userspace tools are now available on 64bit Debian.
=> tests: Enable LVM VDO tests on Debian

src/plugins/smart/smart-common.c
Surprising discovery by reading libatasmart sources. Haven't found any other public mention and found this quite useful.
=> smart: Clarify use of ID_ATA_SMART_ACCESS udev property

.gitignore, Makefile.am, configure.ac, tests/Makefile.am, tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/vfat_test.py, tests/library_test.py, tests/loop_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/nvdimm_test.py, tests/nvme_test.py, tests/overrides_test.py, tests/part_test.py, tests/s390_test.py, tests/smart_test.py, tests/smartmontools_test.py, tests/swap_test.py, tests/utils.py
Fixes: #943
The `config_h.py` file functionality is basically copy-pasted from udisks.
=> Skip tests for plugins disabled during compile time

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c
Make sure users understand that these function don't work with the global LVM lvm.conf config file.
=> lvm: Clarify the global config functionallity in libblockdev

src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme.h
For some reason this is causing more harm and seems to work fine when absent.
=> nvme: Avoid element-type g-i annotations

NEWS.rst, configure.ac, dist/libblockdev.spec.in
We did a new bugfix release from `3.2.x-branch` so we need to bump the version here as well so we are not behind on `master`
=> Version bump to 3.2.1

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py, tests/skip.yml
Follow-up for https://github.com/storaged-project/libblockdev/pull/730
=> lvm-dbus: Add support for repairing RAID LVs

tests/kbd_test.py
The test started failing on Debian with the zram module being busy lets try to add 1s sleep after the swapoff before running rmmod.
=> tests: Try waiting before removing zram module in KBD tests

tests/crypto_test.py
There are some new stricter rules for FIPS in RHEL/CentOS 10 and we are not able to generate a self-signed certificate for testing that wouldn't be rejected by NSS. There might be a workaround for this, but I wasn't able to find one.
=> tests: Skip escrow tests in FIPS mode

plans/udisks.fmf
The /etc/udev/rules.d/60-cdrom_id.rules udev rule shipped by it breaks UDisks tests.
See https://github.com/storaged-project/udisks/pull/1346
=> ci: Remove amazon-ec2-utils if installed

plans/udisks.fmf
The playbook is now split into a playbook and a separate file with tasks. We need both and prepare cannot download two files.
=> ci: Manually download udisks playbooks for revdeps tests

misc/libblockdev-tasks.yml
We can just pass a list of packages to the package module, when using "with_items" ansible installs the packages one by one which is significantly slower.
On a system with all dependencies already present.
Before:
real    0m57,237s
user    0m3,023s
sys     0m1,783s
After:
real    0m9,712s
user    0m1,170s
sys     0m0,512s
=> misc: Do not use "with_items" when installing packages

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, tests/lvm_dbus_tests.py, tests/lvm_test.py
Just a simple API using the lvmconfig command.
=> lvm: Add support for reading lvm.conf

tests/lvm_dbus_tests.py, tests/lvm_test.py
LVM VDO still uses the vdoformat binary which might not be available everywhere.
Related: https://github.com/storaged-project/udisks/issues/1353
=> tests: Skip LVM VDO tests if 'vdoformat' is not available

configure.ac, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
This will be used to set the allow-discards flag on LUKS devices during installation by Blivet.
=> crypto: Add a function to set persistent flags for LUKS

docs/libblockdev-sections.txt
=> docs: Add missing functions to docs/libblockdev-sections.txt

src/plugins/smart/libatasmart.c
The libatasmart attribute overall status differs slightly from the drive SMART self-assessment and is very sensitive for particular status values. Such status should fit more like a pre-fail warning, no reason to fail hard the global assessment. Even a single reallocated sector would cause a warning, while the drive could be quite healthy otherwise.
=> smart: Use drive self-assessment as an overall status

tests/skip.yml
Something changed in the latest 6.15 RC and the "fake" NVDIMM device we use for testing no longer supports sector mode.
The nvdimm plugin is deprecated so I don't really want to try to fix the tests. If this starts to fail on more distributions, I will just skip the entire test suite.
=> tests: Skip NVDIMM reconfigure tests on rawhide

plans/blivet.fmf
Blivet recently renamed the master branch to main.
=> ci: Switch branch for Blivet revdeps tests to 'main'

tests/nvme_test.py
When calling nvme_get_log_sanitize() on a namespace device through io_uring codepath, return codes may differ slightly. This is perfectly fine, subject to the kernel implementation. In this case the errno 22 comes directly from io_uring_wait_cqe().
Fixes #1101
=> tests: Fix NVMe sanitize log return codes

tests/skip.yml
The NVDIMM plugin is deprecated and no longer supported and the fake in-memory NVDIMM namespace we are using in testing is not working correctly with latest kernel.
Related: #1099
=> tests: Skip NVDIMM tests completely

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm/lvm-common.c, src/plugins/lvm/lvm-dbus.c, src/plugins/lvm/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
=> lvm: Add support for running vgcfgbackup/restore

tests/skip.yml
Bug in cryptsetup causes abort so we want to skip this particular test case to be able to finish the tests.
=> tests: Temporarily skip CryptoTestOpenClose with LUKS1 on rawhide

tests/skip.yml
Race condition when trying to remove the disk, reported against C10S as RHEL-100004.
=> tests: Skip MDTestNominateDenominate in RHEL/CentOS 10

.packit.yaml, plans/tests-rhel.fmf
The idea is to have the same configuration both here and on the rhel10-branch (with only the appropriate tests for the branch running) so we can do rebases on the rhel10-branch without losing the RHEL-specific configuration.
See https://github.com/storaged-project/libblockdev/pull/1114 for more details.
=> Sync rhel10-branch CI configuration to master

src/plugins/btrfs.c, tests/btrfs_test.py
=> Fix parsing subvolumes with spaces in name

src/plugins/crypto.c, tests/_lvm_cases.py, tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/exfat_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/mount_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/udf_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py, tests/loop_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/nvme_test.py, tests/part_test.py, tests/run_tests.py, tests/s390_test.py, tests/smart_test.py, tests/smartmontools_test.py, tests/swap_test.py, tests/utils.py
The biggest change is using some extra pbkdf parameters when creating LUKS format to speedup the crypto tests and for other tests making sure we don't create more disks than needed.
On my machine on master the entire test suite currently takes about 2000 seconds, with these changes it's around 1400 seconds so 10 minutes less.
=> Tests speedup

src/plugins/lvm/lvm-dbus.c, tests/_lvm_cases.py
GLib really dislikes us calling 'g_variant_builder_end' on the empty array in this case.
=> lvm-dbus: Fix calling lvcreate with empty list of PVs

tests/nvme_test.py, tests/utils.py
Fixes #1080 
This PR addresses the timing issue where NVMe namespace devices may not be immediately available after controller creation, causing intermittent test failures.
The current implementation performs immediate device lookup without considering that NVMe devices may need time to appear in the system after target creation and connection.
Instead of the simple `sleep(1)` approach proposed in #1081, this implements an intelligent polling mechanism with exponential backoff:
- **Smart Polling**: 100ms initial delay with 1.2x exponential backoff (capped at 500ms)
- **Reasonable Timeout**: 5-second default timeout (configurable)
- **Device Readiness**: Includes `udevadm settle` to ensure proper device initialization
- **Early Return**: Returns immediately when devices are found
- …
=> tests: Fix NVMe device timing issues with intelligent polling mechanism

src/plugins/fs/generic.c, src/plugins/lvm/lvm-dbus.c
Second batch of issues found by static analysis -- unreachable code in LVM DBus and checked return in FS plugin.
=> More static analysis issues fixes

src/plugins/fs/generic.c, src/plugins/fs/mount.c, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/utils.py
Originally reported against LVM and their fsresize helper script: https://github.com/lvmteam/lvm2/issues/182
=> Preserve XFS quota options in temporary mounts 
