src/plugins/mdraid.c, tests/md_test.py, tests/mdadm_fw_raid_examine/mdadm
Follow-up fixes for [rhbz#1207317] (https://bugzilla.redhat.com/show_bug.cgi?id=1207317)
=> FW RAID fixes

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/Makefile.am, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_test.py
Useful and needed by storaged.
=> Add a function for renaming VGs

src/lib/Makefile.am, src/lib/plugin_apis/lvm.api, src/plugins/Makefile.am, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
=> Add the bd_lvm_lvrename() function

Makefile.am
Python 3 is more important for us than Python 2 now.
=> Use ipython3 for debugging and testing sessions

src/plugins/crypto.c, src/plugins/kbd.c, tests/crypto_test.py
=> Make error messages locale agnostic

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, tests/fs_test.py
We already have support for the *ext4* file system. *xfs* is the other one that is most commonly used, so it should be supported too.
=> XFS support

src/plugins/part.c, tests/part_test.py
All the real work is in the second commit which actually fixes the problems reported in the issue #82 and describes what the problem was.
=> Optimal align fix

dist/libblockdev.spec.in, src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
These commits add the extra GPT functionality requested in the issue #80.
=> Extended GPT support

src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
These commits implement extra features identified as useful by [analysis of blivet and its use of parted](https://gist.github.com/vpodzime/5ad01d65f76551016d4f0bd98c3060d5) .
The first three patches can be ignored as they are part of the PR #87
=> Tips from blivet

features.rst, src/plugins/part.c
The first commit is a minor fixup of the *features.rst* file, the second one adds the actual documentation to the *part* plugin.
=> Part plugin docs

docs/libblockdev-sections.txt, src/lib/plugin_apis/btrfs.api.in, src/lib/plugin_apis/fs.api, src/lib/plugin_apis/kbd.api, src/lib/plugin_apis/lvm.api, src/lib/plugin_apis/mdraid.api, src/lib/plugin_apis/part.api
Documentation for structs and a few missing items added to the right places.
=> Documentation improvements

dist/libblockdev.spec.in, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
This is a very useful piece of information when trying to determine what the
relations between LVs are together with the roles of such LVs in those
relations.
=> Include the LV roles in the LVdata

README.DEVEL.rst
For future developers and contributors as well as package maintainers.
=> Add the developer documentation file

src/plugins/lvm-dbus.c, src/plugins/lvm.c
The only operation that LVM CLI provides some progress for is 'pvmove' which we
already have covered (the recent proof-of-concept). For other operations we have
no idea so we can just report start and finish which is done by our exec*
functions being used. The only exception are two cache-related functions which
perform multiple steps/operations allowing us to report progress based on that.
The DBus API may or may not provide progress for any operation (method call) and
we are prepared to handle that. So again nothing to do here except for the two
cache-related functions which can use the same trick as mentioned above.
=> Add progress reporting to the LVM plugins

src/plugins/lvm.c, src/plugins/swap.c, src/utils/Makefile.am, src/utils/exec.c, src/utils/exec.h
This is the first plugin to get the progress reporting where applicable so it of course revealed many small issues that needed fixing first. That's what the first 3 patches do, the last one adds some rudimentary progress reporting to the *swapon()* function which is the only one containing multiple steps allowing us to report at least some progress.
=> Progress reporting - the 'swap' plugin

src/plugins/part.c
There's nothing we can do regarding any real progress reporting because all the
changes happen at once when the model is committed to disk, but we need to
report start and end of each action.
=> Add progress reporting for the part plugin functions

src/plugins/fs.c
=> FS plugin progress reporting

src/plugins/crypto.c
The bd_crypto_luks_format() function does multiple steps allowing us to do some
granular progress reporting. Others are just single calls to libcryptsetup that
don't provide any progress for us to propagate.
=> Add progress reporting to the crypto plugin

src/plugins/kbd.c
Not much we can do here apart from reporting actions starting a finishing.
=> Add progress reporting to the KBD plugin

src/plugins/mpath.c
The only function from the mpath plugin for which progress reporting makes sense
(even if just start and end) and which is not covered by the generic code in the
exec* functions.
=> Add progress reporting to the get_mpath_members() function

src/plugins/s390.c
First commit adds the actual progress reporting the other two are just unrelated minor fixes for the s390 plugin.
=> s390 progress reporting

src/lib/plugin_apis/kbd.api, src/plugins/kbd.c, src/plugins/kbd.h, src/python/gi/overrides/BlockDev.py, tests/kbd_test.py
The kernel API now supports such operations so we should support them too.
=> Add functions for adding/removing single zRAM devices

src/plugins/kbd.c
There may be some dirty blocks that need to be flushed first. Let's check the
bcache's status and wait until it reports that there's actually no cache
attached.
=> Make sure the cache is detached in bcache_detach()

scripts/boilerplate_generator.py, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/kbd.c, src/plugins/lvm-dbus.c, src/plugins/part.c
So that they can clean after themselves when being unloaded.
=> Add close_plugin() functions to plugins

src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
storaged supports this so we should too in order to be a good backend for it.
=> Allow a LUKS device to be activated as read-only

src/plugins/part.c
libparted does committing of a new partition table to disk in two steps:
1. committing (writing and flushing) to disk and
2. telling OS about the partitions.
However, that means that if things go wrong, udev may step in between the above
steps and trigger events when the block device file is closed (from being opened
RW) that could lead to a failure of the second step because some other process
may open the block device file in the reaction to the event.
=> Prevent issues between libparted and udev

README, README.DEVEL.rst, src/plugins/part.c
A few little tweaks we need to do before we reach the 2.0 release milestone.
=> Pre-release housekeeping

dist/libblockdev.spec.in, docs/libblockdev-sections.txt, src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
=> Add support for setting part id (part type) on msdos part tables

src/plugins/fs.c
Just make sure to return false if any of the checks fail.
=> Fix dependency check in fs plugin

Makefile.am, src/plugins/btrfs.c, src/utils/exec.c, tests/utils_test.py
These make the utils tests run, fix one of the tests and fix an issue the test would have discovered if it was correct and run.
=> utils fixes

src/plugins/part.c
Something else (e.g. the caller) may be holding a shared lock on the device
which means libblockdev cannot get an exclusive one. A shared lock should be
okay as it is enough for preventing udev from calling the BLKRRPART ioctl() on
the device which is the major source of issues. There's still a possibility that
something else will step in because with a shared lock udev triggers events on
the device, but that has very small chance of affecting us. And we don't need to
open the file as RDWR because we are not blocking udev from triggering events.
Also, don't strictly require the lock. If we fail to get it, we can just move on
hoping for the best, there will still be chances that things will work just fine
(quite high, actually, because not getting the lock means somebody's holding an …
=> Do not require an exclusive lock on the device to commit part stuff

src/lib/plugin_apis/fs.api, src/plugins/fs.c
typo.
Signed-off-by: Andy Grover <agrover@redhat.com>
=> Fix misspelling

acinclude.m4, configure.ac, src/plugins/fs.c, src/plugins/s390.c, tests/fs_test.py, tests/s390_test.py
These fixes address the following minor issues reported here at GH:
=> A few minor fixes

tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/fs_test.py, tests/kbd_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/part_test.py, tests/swap_test.py, tests/utils.py
These are much more similar to real HW than loop (``losetup``) devices.
=> Use LIO devices for tests

src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/utils.py
Plus fix an issue with LIO devices not being properly recognized/identified in tests sometimes.
=> Fix ``lvremove`` if DISCARD is enabled (#1426849)

src/plugins/lvm-dbus.c, src/utils/extra_arg.c
Few fixes for how extra parameters are constructed when doing DBus calls in *lvm-dbus*.
=> DBus extra params

configure.ac, dist/libblockdev.spec.in, docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/fs.api, src/plugins/Makefile.am, src/plugins/fs.c, src/plugins/fs.h, src/python/gi/overrides/BlockDev.py, tests/fs_test.py, tests/utils.py
Added functions:
- bd_fs_mount
- bd_fs_unmount
=> Add functions for mounting and unmounting filesystems

src/plugins/fs.c
Mount syscall fails for read-only devices (when not mounted as
read-only) with EROFS. In this case mount command tries to mount
the device again as read-only and we should do the same.
=> Fix mounting read-only devices

src/plugins/kbd.c, tests/kbd_test.py
'old' files like 'num_writes' don't exist on newer kernels, but
'new' files like 'io_stats' don't exist on older kernels. So we
need to support both.
=> Use both 'old' and 'new' sysfs files to read zRAM stats

src/plugins/loop.c
The 'autoclear' flag of loop devices can either be read from /sys
or by doing an ioctl() on the device. While the latter one is
simpler and cheaper it may not work 100 % of time due to
interactions with udev. Acquiring an flock() for the time doing
the ioctl() often causes udev to not update its database (in
time). So reading the flag from /sys is safer and thus should be
preferred.
=> First try to read the 'autoclear' flag from /sys/

src/python/gi/overrides/BlockDev.py
If bd_fs_wipe() is called on a device where there's nothing to
wipe (i.e. no signature) an error/exception with a special code
and message is raised. There should be a special python exception
for this case in Python too, otherwise the user code has to catch
all the FSError exceptions and check their messages.
=> Use a special exception for no fs signature when doing wipe

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, tests/fs_test.py
Added bd_fs_clean() function that removes all signatures from given
device.
=> Add a function for cleaning a device

data/conf.d/Makefile.am, dist/libblockdev.spec.in, src/plugins/lvm.c, tests/fs_test.py, tests/kbd_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/utils.py
This is an attempt to stabilize *libblockdev* tests once again because otherwise they are just failing horribly every time they are run.
=> Test fixes

src/plugins/crypto.c, tests/fs_test.py, tests/utils.py
Fix a segmentation fault and leaked file descriptor messages.
=> Misc fixes

configure.ac, src/plugins/fs.c, tests/fs_test.py
This should fix failing *udisks* tests.
=> Fix read-only device mounting (with new libmount)

dist/libblockdev.spec.in
We have moved the repo under a different project at GitHub.
=> Update the project/source URL in the spec file

tests/fs_test.py
Otherwise we don't catch issues in how the generic resize passes
everything to specificy resize functions.
Resolves: #243
=> Check resulting FS size in tests for generic FS resize

tests/fs_test.py
Otherwise trying to get the information about the file system may
fail randomly.
=> Do not verify vfat FS' size after generic resize

tests/btrfs_test.py, tests/crypto_test.py, tests/dm_test.py, tests/fs_test.py, tests/kbd_test.py, tests/library_test.py, tests/loop_test.py, tests/lvm_test.py, tests/mdraid_test.py, tests/mpath_test.py, tests/part_test.py, tests/s390_test.py, tests/swap_test.py, tests/utils.py, tests/utils_test.py
Few changes that allow running tests on Debian.
=> Debian test fixes

src/plugins/part.c
After the new partition table was committed
it takes some time until the partition block
device appears again. If the resize would not
have any effect this is skipped and otherwise
it is waited until the resize result is available.
=> Wait for resized partition

dist/libblockdev.spec.in
=> Own directories /etc/libblockdev and /etc/libblockdev/conf.d

docs/libblockdev-sections.txt, src/lib/blockdev.c.in, src/lib/plugins.h
=> Add a function for getting plugin name

configure.ac, dist/libblockdev.spec.in, src/lib/Makefile.am, src/lib/plugin_apis/s390.api, src/plugins/Makefile.am, src/plugins/s390.c, src/plugins/s390.h, tests/s390_test.py
Added support for disabling s390 plugin and fixed some bugs found when testing the changed.
Fixes #274
=> Various s390 plugins fixes

Makefile.am, NEWS.rst, dist/libblockdev.spec.in
Add NEWS.rst file with release information.
Fixes #257
=> Add NEWS file

tests/kbd_test.py
Use kernel version to pick right test instead of checking
distribution name/version.
=> Better handle old and new zram sysfs api in tests

docs/libblockdev-sections.txt, src/lib/plugin_apis/dm.api, src/plugins/dm.c, src/plugins/dm.h, tests/dm_test.py
added function to get DM device subsystem using device mapper
added tests for this function
=> Added function to get DM device subsystem

tests/btrfs_test.py
'subvolumes list' outputs non-existent subvol after removing
a subvolume.
=> Skip btrfs subvolume tests with btrfs-progs 4.13.2

src/lib/blockdev.c.in, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/fs.c, src/plugins/kbd.c, src/plugins/lvm.c, src/plugins/mdraid.c, src/plugins/part.c, src/utils/exec.c
Fixes for various coverity issues.
Remaining issues: https://vtrefny.fedorapeople.org/misc/scan-results.html
=> Fixes for issues discovered by coverity

.gitignore, configure.ac, dist/libblockdev.spec.in, src/lib/blockdev.pc.in, src/utils/Makefile.am, src/utils/blockdev-utils.pc.in
* new pkgconfig definitions for the *utiils* library
* respecting version in the main library's pkgconfig definitions
=> pkgconfig file improvements

HACKING.md
Describing coding style rules and how to do releases.
=> Add a HACKING.rst file

docs/libblockdev-docs.xml.in, tests/README.rst, tests/run_tests.py
New link to online version and some new ways how to run the tests.
=> Testing documentation update

src/plugins/crypto.c, tests/crypto_test.py, tests/utils.py
Support for creating LUKS 2 format and support for LUKS 2 resizing
are not part of this PR.
=> Add support for LUKS 2 opening and key management

src/plugins/crypto.c, src/plugins/fs/vfat.c, src/plugins/part.c, src/utils/exec.c
Fixed multiple things such as improper initializatons of structs,
and type conversion issues.
=> Fix build with clang

src/plugins/nvdimm.c
ndctl utility now prints sector size for all namespaces that are
not in DAX mode, not only for namespaces in sector/block mode, so
we should do that too.
=> Get sector size for non-block NVDIMM namespaces too

configure.ac, docs/libblockdev-sections.txt, src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, src/utils/exec.c, src/utils/exec.h, tests/crypto_test.py
This adds support for creating LUKS 2 format, including LUKS 2 with integrity.
Fixes #315
=> LUKS 2 format support

features.rst, specs.rst
We forgot to update these files for quite a long time and we have
some new supported technologies/features now.
=> Update specs.rst and features.rst

src/plugins/fs/mount.c, tests/fs_test.py
Both `mnt_context_mount` and `mnt_context_umount` can return zero
even if the (un)mount failed. This happens when using the (un)mount
helper program (e.g. mount.ntfs), in this case we need to get the
return code using `mnt_context_get_helper_status`.
=> Always check for error when (un)mounting

tests/vdo_test.py
Requires partitioning of the backing device.
=> vdo: Add tests for bd_vdo_grow_physical()

configure.ac
Example: https://paste.fedoraproject.org/paste/Bovm4rA8tUNpLEOc9C3Oew
=> Show simple summary after configure

configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am, src/plugins/crypto.c
It is better than reading whole LUKS header just to check if a
device has LUKS format or not.
=> Use libblkid in bd_crypto_is_luks

dist/libblockdev.spec.in, src/python/gi/overrides/Makefile.am
and also start again building with python2 on current rawhide.
=> Fix python2 build on rawhied

src/utils/module.c
bd_utils_have_kernel_module checks if a kernel module is present on the
system. If the module is built-in, it is reported as not present
(issue #314).
Test Plan:
Built libblockdev and made sure that `btrfs` is visible even as a built-in module:
```
[anaconda root@host lib]# python3
Python 3.6.5 (default, Apr 23 2018, 22:53:50) 
[GCC 8.0.1 20180410 (Red Hat 8.0.1-0.21)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("BlockDev", "2.0")
>>> 
>>> from gi.repository import BlockDev as blockdev
>>> 
>>> blockdev.utils_have_kernel_module('btrfs')
True
>>>
```
Module is built-in:
```
[anaconda root@host lib]# cat /usr/lib/modules/`uname -r`/modules.builtin | grep btrfs …
```
=> module.c: Accept kernel modules if they are built-in

dist/libblockdev.spec.in, docs/libblockdev-sections.txt, src/lib/Makefile.am, src/plugins/check_deps.c, src/plugins/check_deps.h, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/utils/Makefile.am, src/utils/dbus.c, src/utils/dbus.h, src/utils/utils.h, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/swap_test.py, tests/utils.py
=> Fix dependency checks in "bd_lvm_is_tech_avail"

src/plugins/lvm-dbus.c, tests/lvm_dbus_tests.py
Type of xtra parameters from functions like pvremove is tuple of
variants '(v)' so it is necessary to "extract" the dict out of it
to add it to the dictionary builder.
----
Unfortunately `g_variant_builder_add_value` only prints warning when you try to add a value with wrong type. And we didn't notice we are actually not calling pvremove with `-ff --yes` until now.
=> lvm-dbus: Fix parsing extra arguments for LVM methods calls

configure.ac, dist/libblockdev.spec.in, src/plugins/Makefile.am, src/plugins/part.c
These commit implement the basic functionality of the *part* plugin using *libfdisk*.
=> libfdisk-based part plugin - basics

README.DEVEL.rst, misc/Vagrantfile.tmpl
See the first commit for details.
=> Vagrantfile template

.gitignore, Makefile.am, README.DEVEL.rst, configure.ac, dist/libblockdev.spec.in, src/plugins/lvm-dbus.c, src/plugins/lvm.c, tools/Makefile.am, tools/lvm-cache-stats.c
More to come in the future, hopefully.
=> The first libblockdev-based mini-tool.

configure.ac, src/plugins/Makefile.am, src/plugins/swap.c
libblkid probe is more reliable than our custom check.
=> Use libblkid to check swap status before swapon

tests/vdo_test.py
growPhysical is broken on partitions.
=> Skip VDO grow physical test

configure.ac, src/plugins/Makefile.am, src/plugins/part.c, tests/part_test.py, tests/utils.py
The easy part (GPT) is finished. "Flags" for msdos will be more complicated, because most of the parted flags exist only in parted (and are not actually flags).
=> Use libfdisk to set and get partition flags

dist/libblockdev.spec.in, misc/Vagrantfile.tmpl
autoconf-archive dependency was added in #418
=> Vagrant template and spec update

src/plugins/swap.c, tests/swap_test.py
'bd_utils_resolve_device' returns already resolved part, there is
no '../' to remove.
=> Fix checking swap status on lvm/md

dist/libblockdev.spec.in
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Sync spec file with python2 obsoletion added downstream

src/lib/plugin_apis/lvm.api, src/plugins/lvm.c, src/utils/exec.c
Collection of fixes found by running udisks under valgrind. Executed our d-bus test suite so far. First priority is the leaking LVM plugin...
See related https://github.com/storaged-project/udisks/pull/659 udisks fixes
=> WIP: Memory leaks

docs/libblockdev-sections.txt, features.rst, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, src/plugins/fs/mount.c, src/plugins/fs/mount.h, tests/fs_test.py
=> Add function for (un)freezing filesystems

scripts/boilerplate_generator.py, src/plugins/fs/ext.c, src/plugins/fs/ntfs.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c
These shouldn't be publicly visible.
=> Hide some "private" functions

src/utils/exec.c
exit_status set by g_spawn_sync is the wait status from waitpid,
not the process exit code. We need to use g_spawn_check_exit_status
to get that.
Taken from #452. The F2FS support needs some changes, but we should merge this fix as soon as possible because it affects all `bd_utils_exec_` functions.
=> Fix how we get process exit code from g_spawn_sync

src/utils/module.c
=> Redirect libkmod log to libblockdev log

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_test.py
Helper function that gets info for the filesystem and calculates
its size.
Fixes: #477
=> Add a generic function to get size of a filesystem

src/plugins/fs/mount.c, tests/fs_test.py
We need to check if the value was "0", not option itself.
=> fs: Fix checking for UID/GID == 0

src/lib/plugin_apis/lvm.api, src/plugins/check_deps.c, src/plugins/check_deps.h, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, src/python/gi/overrides/BlockDev.py, src/utils/exec.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
Work in progress support for VDO in LVM. Only cli plugin for now, I'm posting this here mostly to discuss the proposed API.
=> LVM VDO support

src/plugins/fs/xfs.c
Getting UUID using 'xfs_admin' is currently broken and it's better
to use library where we can.
=> Use libblkid to get label and UUID for XFS filesystems

tools/lvm-cache-stats.c
Useful for machine processing of the stats.
=> Add support for JSON output from lvm-cache-stats

src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/generic.c, src/plugins/fs/reiserfs.c, src/plugins/fs/reiserfs.h, src/python/gi/overrides/BlockDev.py, src/utils/exec.c, src/utils/exec.h, tests/fs_test.py
First three commits are taken from #506. I have also found few f2fs issues when working this, these should be fixed now and f2fs tests should be actually running again.
=> ReiserFS support

tests/run_tests.py
Unfortunately the pdb is started at the point where the exception is raised so for failed assertions you'll end up in the unittest code and have to jump few levels up to the actual test but I didn't find any way how to workaround this.
=> tests: Add option to run pdb for failed tests

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
Small helper function for Blivet similar to bd_lvm_thlvpoolname.
=> lvm: Add a function to get VDO pool name for a VDO LV

src/plugins/fs/mount.c, src/plugins/vdo.c, src/utils/exec.c
=> Memory leaks #3

src/plugins/dm.c, src/plugins/mdraid.c, tests/mdraid_test.py
=> Do not try to activate already active RAID devices

HACKING.md, docs/libblockdev-docs.xml.in, misc/PythonDocs.Dockerfile, src/lib/plugin_apis/crypto.api
Fixes: #427
This is my first real experience with buildah and containers so I hope it makes at least a little sense :-)
=> Python bindings documentation

src/plugins/fs/vfat.c
fsck.vfat returns 1 ("Recoverable errors have been detected") even
when all the errors were successfully fixed so we should not set
error in this case.
Fixes: #550
=> fs: Ignore return code 1 during VFAT repair

configure.ac, dist/libblockdev.spec.in, docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/common.c, src/plugins/fs/common.h, src/plugins/fs/ext.c, src/plugins/fs/ext.h, src/plugins/fs/ntfs.c, src/plugins/fs/ntfs.h, src/plugins/fs/reiserfs.c, src/plugins/fs/reiserfs.h, src/plugins/fs/xfs.c, src/plugins/fs/xfs.h, tests/fs_test.py
=> fs: Add functions to check filesystem UUID validity

configure.ac, dist/libblockdev.spec.in, src/lib/plugin_apis/part.api, src/plugins/Makefile.am, src/plugins/part.c, tests/part_test.py, tests/utils.py
Fixes: #245
So, this is finally it. After nearly 2 years we have the final version of the libfdisk rewrite of the part plugin.
I'll keep this as a draft for now. I plan to go through the code once more and make sure nothing got broken during the countless rebases etc. I also plan to go through the tests and make sure all corner cases are covered and also run the UDisks test suite with this version.
All parts of this PR have been reviewed before (except the last two commits I added today) but feel free to review this again. But this should really be the final version and I plan to fix smaller issues like #557 separately.
=> libfdisk based part plugin

dist/libblockdev.spec.in
=> spec: Remove gdisk dependency

src/plugins/crypto.c, src/plugins/dm.c, src/plugins/dm_logging.c, src/plugins/fs/mount.c, src/plugins/kbd.c, src/plugins/lvm-dbus.c, src/plugins/mdraid.c, src/plugins/swap.c, src/utils/logging.c, src/utils/module.c
Coverity found some new (or actually old) memory leaks.
=> Coverity fixes

src/utils/exec.c, src/utils/exec.h, tests/utils_test.py
#544 and #572 for 2.x-branch
A lot of conflicts in this one so creating a PR to test the changes in our CI.
=> 2.x-branch exec functions fixes

src/plugins/fs/exfat.c, src/plugins/fs/generic.c, tests/fs_test.py
Two issues overlooked when switching exFAT support to exfatprogs.
=> Two small exFAT fixes

src/plugins/loop.c
LOOP_SET_STATUS64 ioctl can fail with EAGAIN so we should try to
run it again instead of failing immediately.
=> loop: Retry LOOP_SET_STATUS64 on EAGAIN

src/plugins/fs/ext.c
=> fs: Do not report error when errors were fixed by e2fsck

src/plugins/fs/common.c
When wiping filesystem signatures from a device, we are not trying
to wipe all signatures, but only signatures matching the filesystem
name -- so for example all "ntfs" signatures.
This makes sense for FAT with multiple "vfat" signatures, but
NTFS has one "ntfs" signature and one nested "dos" partition table
which we also need to remove.
This change makes sure all signatures (no only filesystem ones and
not only these matching the filesystem name) are wiped from the
device.
-----
I'm working on some filesystem plugin test changes and I noticed there are some missing tests for NTFS so I added those and found this issue. I'm posting this for a separate review because it's quite big change and it can potentially break something. Alternative approach would be to change this behaviour only for …
=> fs: Wipe all signatures when running wipe with wipe_all set to TRUE

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.c, src/plugins/fs.h, src/plugins/fs/Makefile.am, src/plugins/fs/generic.c, src/plugins/fs/udf.c, src/plugins/fs/udf.h, src/python/gi/overrides/BlockDev.py, tests/fs_tests/__init__.py, tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/udf_test.py
This also contains #583, I'll rebase it after #583 is merged. The UDF support is quite simple (UDF doesn't support resizing and doesn't have fsck), only complicated thing is mkfs, see the comment below.
=> UDF support

misc/Vagrantfile, misc/install-test-dependencies.yml
and use it in our Vagrantfile.
=> misc: Add ansible playbook to install test dependencies

configure.ac, dist/libblockdev.spec.in, src/lib/plugin_apis/crypto.api, src/plugins/Makefile.am, src/plugins/crypto.c, src/plugins/crypto.h, src/python/gi/overrides/BlockDev.py, tests/crypto_test.py
Just two simple functions to add key to the keyring and open LUKS device using it.
=> Kernel keyring support for crypto plugin

configure.ac, dist/libblockdev.spec.in, misc/install-test-dependencies.yml, src/python/gi/overrides/Makefile.am, tests/btrfs_test.py, tests/crypto_test.py, tests/fs_tests/btrfs_test.py, tests/fs_tests/exfat_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/reiserfs_test.py, tests/fs_tests/udf_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py, tests/part_test.py, tests/run_tests.py, tests/utils_test.py
=> Python 2 support removed

src/utils/dbus.c, src/utils/dev_utils.c, src/utils/exec.c, src/utils/logging.c, src/utils/module.c
Just the utils library for now, I really look forward to doing this for every plugin (it should at least be easier once all the exec functions are "safe").
Related: #527
=> utils: Allow passing NULL for error

src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
=> Allow running info functions on both block and mapped device

src/plugins/fs/btrfs.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/fs/ntfs.c, src/plugins/fs/udf.c, src/plugins/fs/xfs.c
Copy-paste errors, no real difference from a compiler perspective.
=> fs: Fix NULL <--> FALSE return values

src/plugins/fs/vfat.c, tests/fs_test.py
Backport of #618, 2.x will be with us for some time so we need the fix here too.
=> Adapt to dosfstools 4.2 changes

src/plugins/crypto.c, src/plugins/dm.c, src/plugins/fs/mount.c, src/plugins/kbd.c, src/plugins/lvm-dbus.c, src/plugins/mdraid.c, src/plugins/swap.c
Backport of memoery leak fixes from #631 and #571
=> Memory leaks fixes backport

tests/lvm_dbus_tests.py, tests/lvm_test.py
=> Add workarounds for some LVM test issues

tests/fs_tests/fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/xfs_test.py
We prepare an LVM setup for XFS resize tests and currently if one
the steps of pv/vg/lvcreate fails we don't return error and
continue with the test which makes debugging failed tests really
hard. This change makes sure all errors are raised and moves the
LVM code to a function that can be shared in multiple tests.
=> tests: Refactor XFS resize tests

configure.ac
Sorry @vpodzime :-) I've added project URL but I'm not sure how often is this actually used (AFAICT it's visible only in `configure --help`) so it might not be really useful.
=> configure.ac: Remove invalid email address for bug reports

docs/3.0-api-changes.xml
=> docs: Fix opening and ending tag mismatch in 3.0-api-changes.xml

README.md
We already started merging some backward incompatible changes so we should address this in the README.
=> README: Add information about 3.0 and branches

data/conf.d/00-default.cfg, src/plugins/lvm-dbus.c
I plan to do a new release (2.26) later this week so if there is something you want backported let me know.
=> Bugfixes backport for 2.x-branch

src/python/gi/overrides/BlockDev.py, tests/swap_test.py
This fixes exception translation for plugins with multiple
custom exceptions/xrules (currently only swap plugin uses this
functionallity). Currently only the last xrule added to the
ErrorProxy is considered, this fix makes sure all rules are checked
and correct exception is raised.
Backport of #654
=> overrides: Fix translating exceptions in ErrorProxy

src/plugins/vdo_stats.c
The statistics are no longer available in /sys/kvdo, in the latest
version of kvdo we need to use /sys/block/<pool>/vdo/statistics.
Resolves: rhbz#1994220
=> lvm: Fix reading statistics for VDO pools with VDO 8

tests/skip.yml
=> tests: Fix skipping NVDIMM tests on rawhide

src/plugins/lvm.c, tests/lvm_test.py
We use "-o segtypes" for the "lvs" command which means multisegment
LVs will be twice in the output.
See #667
=> lvm: Do not include duplicate entries in bd_lvm_lvs output

tests/crypto_test.py
Backport of #680 and #684 to 2.x to make our CI happy again.
=> Backport fixes for 4k sector size LUKS tests

src/lib/plugin_apis/btrfs.api, src/lib/plugin_apis/crypto.api, src/lib/plugin_apis/dm.api, src/lib/plugin_apis/fs.api, src/plugins/btrfs.c, src/plugins/check_deps.c, src/plugins/crypto.c, src/plugins/dm.c, src/plugins/fs.c, src/plugins/fs/btrfs.c, src/plugins/fs/common.c, src/plugins/fs/exfat.c, src/plugins/fs/ext.c, src/plugins/fs/f2fs.c, src/plugins/fs/generic.c, src/plugins/fs/mount.c, src/plugins/fs/nilfs.c, src/plugins/fs/ntfs.c, src/plugins/fs/reiserfs.c, src/plugins/fs/udf.c, src/plugins/fs/vfat.c, src/plugins/fs/xfs.c
One step closer to fixing #527
=> Allow passing NULL for error (fs and btrfs plugins)

src/lib/plugin_apis/mdraid.api, src/lib/plugin_apis/mpath.api, src/lib/plugin_apis/nvdimm.api, src/lib/plugin_apis/s390.api, src/lib/plugin_apis/swap.api, src/plugins/mdraid.c, src/plugins/mpath.c, src/plugins/nvdimm.c, src/plugins/s390.c, src/plugins/swap.c
This includes mdraid, mpath, nvdimm, s390 and swap plugins. Only part (where I plan to do some unrelated bigger changes first) and lvm (which I'm working on right now) plugins are left.
=> Allow passing NULL for error (part3) 

.lgtm.yml
We need to add dependencies and configure options for LGTM to be
able to analyse the C code.
=> Add LGTM.com configuration

src/lib/plugin_apis/nvme.api, src/plugins/nvme/nvme-error.c, src/plugins/nvme/nvme-fabrics.c, src/plugins/nvme/nvme-info.c, src/plugins/nvme/nvme-op.c, src/plugins/nvme/nvme.h
First attempt to handle the `EWOULDBLOCK` errno cases.
=> nvme: Error handling

src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/vdo_stats.c
=> LVM plugin(s): Allow passing NULL for error

src/plugins/part.c, tests/part_test.py
Latest libfdisk added end alignment for newly created partitions
to make sure the partitions is aligned to 4k sectors on 4k disks.
This means partitions created by us are aligned but partitions
resized to the max size are not because we are calculating the
size and not libfdisk. This change makes sure the end sector is
aligned the same way libfdisk does it for new partitions.
=> part: Align end sector when resizing partition to max size

tests/utils.py
Tested on 4.18.0 and nvme-cli-1.16
=> tests: Fix nvme tests for old kernels

scripts/boilerplate_generator.py, src/plugins/crypto.c, src/plugins/kbd.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py
3.0 is still far away so I plan to do one more release from 2.x
=> Bugfixes backport to 2.x

.github/workflows/csmock.yml, .github/workflows/rpmbuild.yml, misc/ci.Dockerfile
Moving rpmbuild tests to a GH actions container too.
=> Run RPM build tests in GitHub actions

src/plugins/fs/generic.c
This function claims to allow passing NULL instead of error so
we need to actually allow it.
These types of bugs are unfortunately hard to catch, because the Python tests always provide errors, I found this one when working on https://github.com/storaged-project/udisks/pull/763
=> fs: Fix optional error handling in fs_mount helper function

docs/libblockdev-sections.txt, src/lib/plugin_apis/nvme.api, src/plugins/nvme/Makefile.am, src/plugins/nvme/nvme-fabrics.c, src/plugins/nvme/nvme-info.c, src/plugins/nvme/nvme-op.c, src/plugins/nvme/nvme.h, tests/nvme_test.py, tests/run_tests.py
=> nvme: Host NQN and Host ID

src/lib/plugin_apis/mdraid.api, src/plugins/mdraid.c, src/plugins/mdraid.h, tests/mdraid_test.py
=> mdraid: Try harder to get container UUID in bd_md_detail

tests/fs_tests/btrfs_test.py, tests/fs_tests/exfat_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/udf_test.py
=> tests: Fix names for FS features tests

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_tests/generic_test.py
=> fs: Add API for getting list of supported filesystems

docs/libblockdev-sections.txt, src/lib/plugin_apis/lvm.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/lvm.h, tests/lvm_dbus_tests.py, tests/lvm_test.py
I think we need all this detail in the upper levels.  For example, to determine whether a top-LV is degraded.
=> lvm: Expose logical volume substructure

src/plugins/lvm-dbus.c
In cases where we don't care about the error we can simply pass
NULL now.
Fixes: #769
=> lvm-dbus: Fix various GError overwrites

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h
And my annual reminder that _someone_ should write a test for this so we don't forget to add new functions to `docs/libblockdev-sections.txt` all the time.
=> Various documentation related fixes

src/plugins/fs/generic.c
=> fs: Fix nilfs2 dependencies

.github/workflows/csmock.yml, .github/workflows/rpmbuild.yml, .lgtm.yml, dist/libblockdev.spec.in, misc/ci.Dockerfile, misc/install-test-dependencies.yml, src/plugins/btrfs.c, src/plugins/dm.c, src/plugins/fs/generic.c, src/plugins/kbd.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/mdraid.c, src/plugins/mpath.c, src/plugins/nvdimm.c, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/mdraid_test.py
Preparing another release from 2.x
=> Backporting bug fixes to 2.x-branch

src/lib/blockdev.c.in, src/lib/plugin_apis/part.api, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/part.c
Final fix for https://github.com/storaged-project/libblockdev/issues/527 I somehow completely forgot about the part plugin.
=> Part plugin: Allow passing NULL for error

dist/libblockdev.spec.in
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> spec: Change licence string to the SPDX format required by Fedora

src/lib/plugin_apis/fs.api, src/plugins/fs/mount.c
=> Clarify the run_as_user option for bd_fs_mount/unmount

HACKING.md, README.DEVEL.rst, README.md, misc/PythonDocs.Dockerfile, misc/install-test-dependencies.yml, scripts/boilerplate_generator.py, src/lib/plugin_apis/lvm.api, src/plugins/crypto.h, src/plugins/lvm-dbus.c, src/plugins/lvm.c, tests/crypto_test.py, tests/library_test.py, tests/lvm_dbus_tests.py, tests/lvm_test.py, tests/nvdimm_test.py, tests/overrides_test.py, tests/run_tests.py, tools/lvm-cache-stats.c
Found by spellintian and codespell.
=> Fix various typos and spelling errors

src/lib/plugin_apis/part.api, src/plugins/part.c, src/plugins/part.h, tests/part_test.py
=> part: Add function to set partition UUID

tests/skip.yml
=> tests: Skip DDF RAID tests on rawhide

configure.ac, src/plugins/nvme/Makefile.am, src/plugins/nvme/nvme-error.c, src/plugins/nvme/nvme-fabrics.c, src/plugins/nvme/nvme-info.c, src/plugins/nvme/nvme-op.c, src/plugins/nvme/nvme.c, tests/nvme_test.py
Just a couple of minor fixes, on par of recent nvme-cli changes.
=> nvme: ID fields fixes

scripts/boilerplate_generator.py
=> Use our logging function instead of g_debug in boilerplate_generator

src/plugins/part.c
=> part: Fix segfault when adding a partition too big for MSDOS

src/plugins/fs/xfs.c
Backport of #871 to 2.x-branch
=> fs/xfs: Open device read-only for xfs_info

.github/workflows/blivet-tests.yml, misc/ci.Dockerfile
Should prevent issues like #875 in the future.
=> ci: Add GH actions job to run Blivet tests on PRs

src/plugins/fs/xfs.c
=> fs/xfs: Use xfs_spaceman instead of xfs_db for mounted filesystems

docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/vfat.c, src/plugins/fs/vfat.h, tests/fs_tests/generic_test.py, tests/fs_tests/vfat_test.py
Support for changing volume ID was added in dosfstools 4.2
=> fs: Add support for setting and checking UUID/volume ID for VFAT

docs/3.0-api-changes.xml, docs/libblockdev-sections.txt, src/lib/plugin_apis/swap.api, src/plugins/swap.c, src/plugins/swap.h, src/python/gi/overrides/BlockDev.py, tests/swap_test.py
=> UUID support for swap

src/lib/plugin_apis/crypto.api, src/plugins/crypto.c, src/plugins/crypto.h, tests/crypto_test.py
Related: https://github.com/storaged-project/udisks/issues/1111
=> crypto: Add support for getting information about BITLK devices

misc/Vagrantfile
New releases added and fixed deprecated disk cache configuration.
=> misc: Update Vagrantfile

docs/3.0-api-changes.xml, docs/libblockdev-sections.txt, src/lib/plugin_apis/fs.api, src/plugins/fs.h, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_tests/btrfs_test.py, tests/fs_tests/ext_test.py, tests/fs_tests/f2fs_test.py, tests/fs_tests/generic_test.py, tests/fs_tests/nilfs_test.py, tests/fs_tests/ntfs_test.py, tests/fs_tests/vfat_test.py, tests/fs_tests/xfs_test.py
Just to be consistent have everything named with the capital FS.
=> fs: Rename BDFs* enums to BDFS*

tests/run_tests.py, tests/utils.py
See also https://github.com/storaged-project/udisks/pull/759
=> tests: Add a special tag to run all tests

src/plugins/fs/ext.c
Follow up for f323141ed831d119e4f858cecb19cbdba7655397 we don't want to log all failures as errors, e2fsck will also print some lines that are not progress.
=> fs: Avoid excess logging in extract_e2fsck_progress

src/plugins/fs/generic.c, tests/fs_tests/generic_test.py
=> fs: Fix leaking directories with temporary mounts

src/plugins/lvm-dbus.c, src/plugins/lvm.c
Depending on how lvresize is compiled, it might default to "--fs checksize", which is not what we want for this low level API.
Also, "--fs checksize" does not always succeed even when the filesystem is the right size, such as when libblkid does not work for NTFS.
=> Always use "--fs ignore" with lvresize

.github/workflows/compilation.yml
=> ci: Add an action to compile libblockdev with different compilers

src/plugins/lvm-dbus.c, src/utils/logging.h
https://bugzilla.redhat.com/show_bug.cgi?id=2247319
=> lvm-dbus: Minor memory allocation fixes

Makefile.am
Two minor issues discovered during the 3.1 release.
Fixes: #996
=> Two small Makefile fixes: tag and bumpver

tests/btrfs_test.py
Re-structure the test classes in the btrfs tests to not always create two lio devices in total this saves ~ 30 seconds on my T14s running the tests in a Fedora VM with 4 cores.
Before:
Ran 24 tests in 99.031s
Ater:
Ran 24 tests in 66.436s
Benchmarks aren't the most accurate but should give a rough estimate.
=> Speed up btrfs tests

src/plugins/lvm-dbus.c
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2247319
=> Fix (potential) crashes in LVM DBus init

src/lib/plugin_apis/fs.api, src/plugins/fs/ext.c
=> fs: Fix docstring for bd_fs_ext?_get_min_size functions

NEWS.rst, configure.ac, src/plugins/smart/libatasmart.c, src/plugins/smart/smartmontools.c
Feel free to rephrase or provide suggestions. The primary idea was to clear confusion about the structure and about the intended use.
=> smart: Documentation

src/lib/plugin_apis/fs.api, src/plugins/fs/generic.c, src/plugins/fs/generic.h, tests/fs_tests/xfs_test.py
The size limits are taken from blivet.
=> fs: Add filesystem size limits to BDFSFeatures

.github/workflows/codeql-analysis.yml, .packit.yaml, Makefile.am, NEWS.rst, README.md, configure.ac, dist/libblockdev.spec.in, misc/install-test-dependencies.yml, plans/blivet.fmf, plans/tests.fmf, plans/udisks.fmf, src/lib/plugin_apis/lvm.api, src/lib/plugin_apis/nvme.api, src/plugins/crypto.c, src/plugins/lvm-dbus.c, src/plugins/lvm.c, src/plugins/nvme/nvme.h, src/plugins/smart/smart-common.c
Backporting some changes from _master_.
=> Prepare 3.2.1 release

.packit.yaml, misc/install-test-dependencies.yml, plans/blivet.fmf, plans/tests-rhel.fmf, plans/tests.fmf, plans/udisks.fmf
Basic CI tasks for running tests on "clean" CentOS 10 Stream.
=> Simple packit and TMT based CI for rhel10-branch

tests/smart_test.py, tests/smartmontools_test.py, tests/utils.py
This was originally one of the issues found by pylint and part of #1119 but for some reason fixing this causes an infinite loop in `_setup_scsi_debug` on Debian and CentOS (but not Fedora). We need some more time to investigate this and it's out of scope for the tests speed up so I am keeping this as a draft for now.
=> tests: Fix SCSI debug disks cleanup in SMART tests
